"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AuthContext(_message.Message):
    """=============================================================================
    Wspólne typy referowane przez control.proto, filesystem.proto, heartbeat.proto.

    Wydzielone do osobnego pliku, żeby:
      - semantyka uwierzytelnienia i znaczników czasu ewoluowała w jednym miejscu;
      - buf-breaking blokował niespójne zmiany na poziomie pojedynczego pliku;
      - nowe plany IPC dodawane w przyszłości dziedziczyły identyczne envelope'y
        bez kopiowania definicji.
    =============================================================================

    Per-frame authentication envelope. WYMAGANE w każdej wiadomości każdego planu.

    Zaadresowane zagrożenia (Red Team, zatwierdzone):
      1. CID collision / spoofing: AF_VSOCK nie posiada peer-identity na poziomie
         transportu. mTLS daje tożsamość na handshake'u, ale dynamiczne CID-y w
         `qemu:///session` mogą zostać zrecyklowane między restartami domeny
         libvirt — frame zaadresowany do nieżyjącej domeny może trafić do nowej.
         Trójka {fingerprint, nonce, sequence} czyni taki misroute wykrywalnym
         po stronie odbiorcy.
      2. Replay attack: monotoniczny `sequence` per-direction wymusza, że każdy
         kolejny frame ma numer dokładnie o 1 większy. Powtórka lub regresja ⇒
         zerwanie strumienia + incident counter.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PEER_CERT_FINGERPRINT_FIELD_NUMBER: _builtins.int
    STREAM_NONCE_FIELD_NUMBER: _builtins.int
    SEQUENCE_FIELD_NUMBER: _builtins.int
    TRACEPARENT_FIELD_NUMBER: _builtins.int
    peer_cert_fingerprint: _builtins.str
    """SHA-256 leaf certyfikatu mTLS peera, lowercase hex, bez separatorów.
    Odbiorca MUSI porównać z fingerprintem zaobserwowanym na warstwie TLS
    dla aktywnego strumienia. Niezgodność ⇒ zamknij strumień.
    """
    stream_nonce: _builtins.bytes
    """Losowy 16-bajtowy nonce, stały przez cały czas życia strumienia.
    Wykrywa przypadek, gdy dwa niezależne strumienie skrzyżują się na
    poziomie vsock z powodu reuse CID.
    """
    sequence: _builtins.int
    """Ściśle monotoniczny licznik per-kierunek (klient i serwer mają osobne).
    Nadawca inkrementuje przed wysłaniem; odbiorca wymusza ścisłe +1.
    """
    traceparent: _builtins.str
    """W3C traceparent header propagated across the host↔guest boundary so
    that a single trace_id ties together host-side dispatch logs and
    guest-side handler logs. Format: "00-<32hex>-<16hex>-<2hex>" (version 0).
    Optional: receivers must tolerate an absent or malformed value — they
    generate a fresh root context rather than rejecting the frame.
    """
    def __init__(
        self,
        *,
        peer_cert_fingerprint: _builtins.str = ...,
        stream_nonce: _builtins.bytes = ...,
        sequence: _builtins.int = ...,
        traceparent: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["peer_cert_fingerprint", b"peer_cert_fingerprint", "sequence", b"sequence", "stream_nonce", b"stream_nonce", "traceparent", b"traceparent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuthContext: _TypeAlias = AuthContext  # noqa: Y015

@_typing.final
class TimingMark(_message.Message):
    """Wall-clock + monotonic shipowane razem.

    Rationale: z samego wall-clocka nie da się odróżnić opóźnienia sieciowego
    od stalla schedulera ani od skoku zegara (NTP jump, hibernate). Para pozwala
    hostowi liczyć sensowne RTT w heartbeat.proto i wykrywać clock drift.
    """

    DESCRIPTOR: _descriptor.Descriptor

    WALL_CLOCK_FIELD_NUMBER: _builtins.int
    MONOTONIC_NS_FIELD_NUMBER: _builtins.int
    monotonic_ns: _builtins.int
    @_builtins.property
    def wall_clock(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        wall_clock: _timestamp_pb2.Timestamp | None = ...,
        monotonic_ns: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["wall_clock", b"wall_clock"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["monotonic_ns", b"monotonic_ns", "wall_clock", b"wall_clock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TimingMark: _TypeAlias = TimingMark  # noqa: Y015
