"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from crossdesk.v1 import control_pb2 as _control_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ControlServiceStub:
    """=============================================================================
    CrossDesk Control Plane — cykl życia sesji + zdarzenia okien RAIL.

    Transport: gRPC over AF_VSOCK z mTLS na warstwie kanału gRPC. Każdy frame
    niezależnie nosi AuthContext (defense-in-depth wobec CID collision i replay
    — patrz common.proto).

    SESSION FSM (driven by ControlService.OpenSession bidi stream):

                   ClientHello                ServerAccept
      HANDSHAKE ───────────────▶ AUTHENTICATING ─────────────▶ AUTHENTICATED
           ▲                            │                              │
           │                            │ AuthFailure                  │ Ready
           └────────────────────────────┘                              ▼
                                                                    READY ◀────┐
                                                                       │      │
                                                     AppLaunchRequest  │      │
                                                                       ▼      │
                                                               LAUNCHING_APP  │
                                                                       │      │
                                                          AppLaunched  │      │
                                                                       ▼      │
                                                               APP_RUNNING ───┘
                                                                       │  AppExit
                                                                       │
                                                     SessionTerminate  │
                                                                       ▼
                                                                 DRAINING
                                                                       │
                                             all RAIL windows closed   │
                                                                       ▼
                                                                 CLOSED (terminal)

    Każdy nieoczekiwany błąd na strumieniu ⇒ CLOSED + tear-down kanału.
    =============================================================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ControlServiceAsyncStub: ...
    OpenSession: _grpc.StreamStreamMultiCallable[_control_pb2.ClientFrame, _control_pb2.ServerFrame]
    """Bidirectional. Host inicjuje; Guest multipleksuje RailWindowEvent i
    AppLifecycleEvent z powrotem tym samym strumieniem, żeby zachować
    kolejność względem komend kontrolnych.
    """

@_typing.type_check_only
class ControlServiceAsyncStub(ControlServiceStub):
    """=============================================================================
    CrossDesk Control Plane — cykl życia sesji + zdarzenia okien RAIL.

    Transport: gRPC over AF_VSOCK z mTLS na warstwie kanału gRPC. Każdy frame
    niezależnie nosi AuthContext (defense-in-depth wobec CID collision i replay
    — patrz common.proto).

    SESSION FSM (driven by ControlService.OpenSession bidi stream):

                   ClientHello                ServerAccept
      HANDSHAKE ───────────────▶ AUTHENTICATING ─────────────▶ AUTHENTICATED
           ▲                            │                              │
           │                            │ AuthFailure                  │ Ready
           └────────────────────────────┘                              ▼
                                                                    READY ◀────┐
                                                                       │      │
                                                     AppLaunchRequest  │      │
                                                                       ▼      │
                                                               LAUNCHING_APP  │
                                                                       │      │
                                                          AppLaunched  │      │
                                                                       ▼      │
                                                               APP_RUNNING ───┘
                                                                       │  AppExit
                                                                       │
                                                     SessionTerminate  │
                                                                       ▼
                                                                 DRAINING
                                                                       │
                                             all RAIL windows closed   │
                                                                       ▼
                                                                 CLOSED (terminal)

    Każdy nieoczekiwany błąd na strumieniu ⇒ CLOSED + tear-down kanału.
    =============================================================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    OpenSession: _aio.StreamStreamMultiCallable[_control_pb2.ClientFrame, _control_pb2.ServerFrame]  # type: ignore[assignment]
    """Bidirectional. Host inicjuje; Guest multipleksuje RailWindowEvent i
    AppLifecycleEvent z powrotem tym samym strumieniem, żeby zachować
    kolejność względem komend kontrolnych.
    """

class ControlServiceServicer(metaclass=_abc_1.ABCMeta):
    """=============================================================================
    CrossDesk Control Plane — cykl życia sesji + zdarzenia okien RAIL.

    Transport: gRPC over AF_VSOCK z mTLS na warstwie kanału gRPC. Każdy frame
    niezależnie nosi AuthContext (defense-in-depth wobec CID collision i replay
    — patrz common.proto).

    SESSION FSM (driven by ControlService.OpenSession bidi stream):

                   ClientHello                ServerAccept
      HANDSHAKE ───────────────▶ AUTHENTICATING ─────────────▶ AUTHENTICATED
           ▲                            │                              │
           │                            │ AuthFailure                  │ Ready
           └────────────────────────────┘                              ▼
                                                                    READY ◀────┐
                                                                       │      │
                                                     AppLaunchRequest  │      │
                                                                       ▼      │
                                                               LAUNCHING_APP  │
                                                                       │      │
                                                          AppLaunched  │      │
                                                                       ▼      │
                                                               APP_RUNNING ───┘
                                                                       │  AppExit
                                                                       │
                                                     SessionTerminate  │
                                                                       ▼
                                                                 DRAINING
                                                                       │
                                             all RAIL windows closed   │
                                                                       ▼
                                                                 CLOSED (terminal)

    Każdy nieoczekiwany błąd na strumieniu ⇒ CLOSED + tear-down kanału.
    =============================================================================
    """

    @_abc_1.abstractmethod
    def OpenSession(
        self,
        request_iterator: _MaybeAsyncIterator[_control_pb2.ClientFrame],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_control_pb2.ServerFrame], _abc.AsyncIterator[_control_pb2.ServerFrame]]:
        """Bidirectional. Host inicjuje; Guest multipleksuje RailWindowEvent i
        AppLifecycleEvent z powrotem tym samym strumieniem, żeby zachować
        kolejność względem komend kontrolnych.
        """

def add_ControlServiceServicer_to_server(servicer: ControlServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
