"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from crossdesk.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ClientFrame(_message.Message):
    """=============================================================================
    Client → Server
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTH_FIELD_NUMBER: _builtins.int
    SENT_AT_FIELD_NUMBER: _builtins.int
    HELLO_FIELD_NUMBER: _builtins.int
    LAUNCH_FIELD_NUMBER: _builtins.int
    FOCUS_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    TERMINATE_FIELD_NUMBER: _builtins.int
    RAIL_EVENT_FIELD_NUMBER: _builtins.int
    VERIFY_CREDENTIALS_RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def auth(self) -> _common_pb2.AuthContext: ...
    @_builtins.property
    def sent_at(self) -> _common_pb2.TimingMark: ...
    @_builtins.property
    def hello(self) -> Global___ClientHello: ...
    @_builtins.property
    def launch(self) -> Global___AppLaunchRequest: ...
    @_builtins.property
    def focus(self) -> Global___AppFocusRequest: ...
    @_builtins.property
    def close(self) -> Global___AppCloseRequest: ...
    @_builtins.property
    def terminate(self) -> Global___SessionTerminate: ...
    @_builtins.property
    def rail_event(self) -> Global___RailWindowEvent: ...
    @_builtins.property
    def verify_credentials_result(self) -> Global___VerifyCredentialsResult: ...
    def __init__(
        self,
        *,
        auth: _common_pb2.AuthContext | None = ...,
        sent_at: _common_pb2.TimingMark | None = ...,
        hello: Global___ClientHello | None = ...,
        launch: Global___AppLaunchRequest | None = ...,
        focus: Global___AppFocusRequest | None = ...,
        close: Global___AppCloseRequest | None = ...,
        terminate: Global___SessionTerminate | None = ...,
        rail_event: Global___RailWindowEvent | None = ...,
        verify_credentials_result: Global___VerifyCredentialsResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth", "close", b"close", "focus", b"focus", "hello", b"hello", "launch", b"launch", "payload", b"payload", "rail_event", b"rail_event", "sent_at", b"sent_at", "terminate", b"terminate", "verify_credentials_result", b"verify_credentials_result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth", "close", b"close", "focus", b"focus", "hello", b"hello", "launch", b"launch", "payload", b"payload", "rail_event", b"rail_event", "sent_at", b"sent_at", "terminate", b"terminate", "verify_credentials_result", b"verify_credentials_result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["hello", "launch", "focus", "close", "terminate", "rail_event", "verify_credentials_result"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ClientFrame: _TypeAlias = ClientFrame  # noqa: Y015

@_typing.final
class ClientHello(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HOST_VERSION_FIELD_NUMBER: _builtins.int
    SUPPORTED_FEATURES_FIELD_NUMBER: _builtins.int
    HOST_DOMAIN_UUID_FIELD_NUMBER: _builtins.int
    PROTOCOL_VERSION_FIELD_NUMBER: _builtins.int
    host_version: _builtins.str
    host_domain_uuid: _builtins.str
    """UUID domeny libvirt po stronie hosta. Guest porównuje z własnym
    SMBIOS-injected UUID, żeby wykryć live-migration / host swap.
    """
    protocol_version: _builtins.str
    """CrossDesk wire-protocol major version. Currently "1". On a major
    version bump the receiver rejects with AuthFailure FEATURE_NEGOTIATION_FAILED
    rather than trying to parse an incompatible frame layout.
    """
    @_builtins.property
    def supported_features(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Capability advertisement; Guest odpowiada wynegocjowanym podzbiorem.
        np. "rail.v1", "virtiofs.jit"
        """

    def __init__(
        self,
        *,
        host_version: _builtins.str = ...,
        supported_features: _abc.Iterable[_builtins.str] | None = ...,
        host_domain_uuid: _builtins.str = ...,
        protocol_version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["host_domain_uuid", b"host_domain_uuid", "host_version", b"host_version", "protocol_version", b"protocol_version", "supported_features", b"supported_features"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientHello: _TypeAlias = ClientHello  # noqa: Y015

@_typing.final
class AppLaunchRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    EXECUTABLE_GUEST_PATH_FIELD_NUMBER: _builtins.int
    ARGV_FIELD_NUMBER: _builtins.int
    REQUIRED_SHARE_ID_FIELD_NUMBER: _builtins.int
    WORKING_DIRECTORY_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    """UUID; koreluje AppLaunched/Failed"""
    executable_guest_path: _builtins.str
    required_share_id: _builtins.str
    """Opcjonalny share_id z filesystem.proto, który MUSI być w stanie ATTACHED
    przed startem procesu. Ustawiany, gdy launch wynika z dwukliku na pliku.
    """
    working_directory: _builtins.str
    """CWD wewnątrz Guesta, zwykle root JIT-mountowanego dysku."""
    @_builtins.property
    def argv(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        executable_guest_path: _builtins.str = ...,
        argv: _abc.Iterable[_builtins.str] | None = ...,
        required_share_id: _builtins.str = ...,
        working_directory: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["argv", b"argv", "executable_guest_path", b"executable_guest_path", "request_id", b"request_id", "required_share_id", b"required_share_id", "working_directory", b"working_directory"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppLaunchRequest: _TypeAlias = AppLaunchRequest  # noqa: Y015

@_typing.final
class AppFocusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    WINDOW_ID_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    window_id: _builtins.int
    """HWND z wcześniejszego RailWindowEvent"""
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        window_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["request_id", b"request_id", "window_id", b"window_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppFocusRequest: _TypeAlias = AppFocusRequest  # noqa: Y015

@_typing.final
class AppCloseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    WINDOW_ID_FIELD_NUMBER: _builtins.int
    FORCE_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    window_id: _builtins.int
    force: _builtins.bool
    """false ⇒ WM_CLOSE; true ⇒ TerminateProcess"""
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        window_id: _builtins.int = ...,
        force: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["force", b"force", "request_id", b"request_id", "window_id", b"window_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppCloseRequest: _TypeAlias = AppCloseRequest  # noqa: Y015

@_typing.final
class SessionTerminate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Reason:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SessionTerminate._Reason.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        REASON_UNSPECIFIED: SessionTerminate._Reason.ValueType  # 0
        REASON_USER_QUIT: SessionTerminate._Reason.ValueType  # 1
        REASON_HOST_SHUTDOWN: SessionTerminate._Reason.ValueType  # 2
        REASON_PROTOCOL_ERROR: SessionTerminate._Reason.ValueType  # 3
        REASON_AUTH_FAILED: SessionTerminate._Reason.ValueType  # 4

    class Reason(_Reason, metaclass=_ReasonEnumTypeWrapper): ...
    REASON_UNSPECIFIED: SessionTerminate.Reason.ValueType  # 0
    REASON_USER_QUIT: SessionTerminate.Reason.ValueType  # 1
    REASON_HOST_SHUTDOWN: SessionTerminate.Reason.ValueType  # 2
    REASON_PROTOCOL_ERROR: SessionTerminate.Reason.ValueType  # 3
    REASON_AUTH_FAILED: SessionTerminate.Reason.ValueType  # 4

    REASON_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    reason: Global___SessionTerminate.Reason.ValueType
    detail: _builtins.str
    def __init__(
        self,
        *,
        reason: Global___SessionTerminate.Reason.ValueType = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionTerminate: _TypeAlias = SessionTerminate  # noqa: Y015

@_typing.final
class ServerFrame(_message.Message):
    """=============================================================================
    Server → Client
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTH_FIELD_NUMBER: _builtins.int
    SENT_AT_FIELD_NUMBER: _builtins.int
    ACCEPT_FIELD_NUMBER: _builtins.int
    AUTH_FAILURE_FIELD_NUMBER: _builtins.int
    LAUNCHED_FIELD_NUMBER: _builtins.int
    LAUNCH_FAILED_FIELD_NUMBER: _builtins.int
    APP_EVENT_FIELD_NUMBER: _builtins.int
    CLOSED_FIELD_NUMBER: _builtins.int
    VERIFY_CREDENTIALS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def auth(self) -> _common_pb2.AuthContext: ...
    @_builtins.property
    def sent_at(self) -> _common_pb2.TimingMark: ...
    @_builtins.property
    def accept(self) -> Global___ServerAccept: ...
    @_builtins.property
    def auth_failure(self) -> Global___AuthFailure: ...
    @_builtins.property
    def launched(self) -> Global___AppLaunched: ...
    @_builtins.property
    def launch_failed(self) -> Global___AppLaunchFailed: ...
    @_builtins.property
    def app_event(self) -> Global___AppLifecycleEvent: ...
    @_builtins.property
    def closed(self) -> Global___SessionClosed: ...
    @_builtins.property
    def verify_credentials(self) -> Global___VerifyCredentialsRequest: ...
    def __init__(
        self,
        *,
        auth: _common_pb2.AuthContext | None = ...,
        sent_at: _common_pb2.TimingMark | None = ...,
        accept: Global___ServerAccept | None = ...,
        auth_failure: Global___AuthFailure | None = ...,
        launched: Global___AppLaunched | None = ...,
        launch_failed: Global___AppLaunchFailed | None = ...,
        app_event: Global___AppLifecycleEvent | None = ...,
        closed: Global___SessionClosed | None = ...,
        verify_credentials: Global___VerifyCredentialsRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["accept", b"accept", "app_event", b"app_event", "auth", b"auth", "auth_failure", b"auth_failure", "closed", b"closed", "launch_failed", b"launch_failed", "launched", b"launched", "payload", b"payload", "sent_at", b"sent_at", "verify_credentials", b"verify_credentials"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accept", b"accept", "app_event", b"app_event", "auth", b"auth", "auth_failure", b"auth_failure", "closed", b"closed", "launch_failed", b"launch_failed", "launched", b"launched", "payload", b"payload", "sent_at", b"sent_at", "verify_credentials", b"verify_credentials"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["accept", "auth_failure", "launched", "launch_failed", "app_event", "closed", "verify_credentials"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ServerFrame: _TypeAlias = ServerFrame  # noqa: Y015

@_typing.final
class ServerAccept(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GUEST_VERSION_FIELD_NUMBER: _builtins.int
    NEGOTIATED_FEATURES_FIELD_NUMBER: _builtins.int
    GUEST_SMBIOS_UUID_FIELD_NUMBER: _builtins.int
    PROTOCOL_VERSION_FIELD_NUMBER: _builtins.int
    guest_version: _builtins.str
    guest_smbios_uuid: _builtins.str
    """p. ClientHello.host_domain_uuid"""
    protocol_version: _builtins.str
    """Echoes the protocol_version the guest is responding under."""
    @_builtins.property
    def negotiated_features(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        guest_version: _builtins.str = ...,
        negotiated_features: _abc.Iterable[_builtins.str] | None = ...,
        guest_smbios_uuid: _builtins.str = ...,
        protocol_version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["guest_smbios_uuid", b"guest_smbios_uuid", "guest_version", b"guest_version", "negotiated_features", b"negotiated_features", "protocol_version", b"protocol_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerAccept: _TypeAlias = ServerAccept  # noqa: Y015

@_typing.final
class AuthFailure(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Code:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AuthFailure._Code.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CODE_UNSPECIFIED: AuthFailure._Code.ValueType  # 0
        CODE_FINGERPRINT_MISMATCH: AuthFailure._Code.ValueType  # 1
        CODE_NONCE_REUSE: AuthFailure._Code.ValueType  # 2
        CODE_SEQUENCE_REGRESSION: AuthFailure._Code.ValueType  # 3
        CODE_UUID_MISMATCH: AuthFailure._Code.ValueType  # 4
        CODE_FEATURE_NEGOTIATION_FAILED: AuthFailure._Code.ValueType  # 5

    class Code(_Code, metaclass=_CodeEnumTypeWrapper): ...
    CODE_UNSPECIFIED: AuthFailure.Code.ValueType  # 0
    CODE_FINGERPRINT_MISMATCH: AuthFailure.Code.ValueType  # 1
    CODE_NONCE_REUSE: AuthFailure.Code.ValueType  # 2
    CODE_SEQUENCE_REGRESSION: AuthFailure.Code.ValueType  # 3
    CODE_UUID_MISMATCH: AuthFailure.Code.ValueType  # 4
    CODE_FEATURE_NEGOTIATION_FAILED: AuthFailure.Code.ValueType  # 5

    CODE_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    code: Global___AuthFailure.Code.ValueType
    detail: _builtins.str
    def __init__(
        self,
        *,
        code: Global___AuthFailure.Code.ValueType = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "detail", b"detail"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuthFailure: _TypeAlias = AuthFailure  # noqa: Y015

@_typing.final
class AppLaunched(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    PROCESS_ID_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    process_id: _builtins.int
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        process_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["process_id", b"process_id", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppLaunched: _TypeAlias = AppLaunched  # noqa: Y015

@_typing.final
class AppLaunchFailed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    NTSTATUS_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    error: _builtins.str
    """human-readable"""
    ntstatus: _builtins.int
    """0 jeśli niezwiązane z Win32"""
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        error: _builtins.str = ...,
        ntstatus: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "ntstatus", b"ntstatus", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppLaunchFailed: _TypeAlias = AppLaunchFailed  # noqa: Y015

@_typing.final
class AppLifecycleEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AppLifecycleEvent._Kind.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        KIND_UNSPECIFIED: AppLifecycleEvent._Kind.ValueType  # 0
        KIND_STARTED: AppLifecycleEvent._Kind.ValueType  # 1
        KIND_EXITED: AppLifecycleEvent._Kind.ValueType  # 2
        KIND_CRASHED: AppLifecycleEvent._Kind.ValueType  # 3

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: AppLifecycleEvent.Kind.ValueType  # 0
    KIND_STARTED: AppLifecycleEvent.Kind.ValueType  # 1
    KIND_EXITED: AppLifecycleEvent.Kind.ValueType  # 2
    KIND_CRASHED: AppLifecycleEvent.Kind.ValueType  # 3

    PROCESS_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    EXIT_CODE_FIELD_NUMBER: _builtins.int
    process_id: _builtins.int
    kind: Global___AppLifecycleEvent.Kind.ValueType
    exit_code: _builtins.int
    def __init__(
        self,
        *,
        process_id: _builtins.int = ...,
        kind: Global___AppLifecycleEvent.Kind.ValueType = ...,
        exit_code: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exit_code", b"exit_code", "kind", b"kind", "process_id", b"process_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppLifecycleEvent: _TypeAlias = AppLifecycleEvent  # noqa: Y015

@_typing.final
class RailWindowEvent(_message.Message):
    """-----------------------------------------------------------------------------
    RAIL (Remote Application Integrated Locally) window events.
    Emitowane przez Guest agent obserwujący top-level okna uruchomionych
    aplikacji; konsumowane przez display engine hosta (FreeRDP/RAIL).
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[RailWindowEvent._Kind.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        KIND_UNSPECIFIED: RailWindowEvent._Kind.ValueType  # 0
        KIND_CREATED: RailWindowEvent._Kind.ValueType  # 1
        KIND_DESTROYED: RailWindowEvent._Kind.ValueType  # 2
        KIND_MOVED: RailWindowEvent._Kind.ValueType  # 3
        KIND_RESIZED: RailWindowEvent._Kind.ValueType  # 4
        KIND_MINIMIZED: RailWindowEvent._Kind.ValueType  # 5
        KIND_MAXIMIZED: RailWindowEvent._Kind.ValueType  # 6
        KIND_RESTORED: RailWindowEvent._Kind.ValueType  # 7
        KIND_FOCUS_GAINED: RailWindowEvent._Kind.ValueType  # 8
        KIND_FOCUS_LOST: RailWindowEvent._Kind.ValueType  # 9
        KIND_TITLE_CHANGED: RailWindowEvent._Kind.ValueType  # 10
        KIND_ICON_CHANGED: RailWindowEvent._Kind.ValueType  # 11

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: RailWindowEvent.Kind.ValueType  # 0
    KIND_CREATED: RailWindowEvent.Kind.ValueType  # 1
    KIND_DESTROYED: RailWindowEvent.Kind.ValueType  # 2
    KIND_MOVED: RailWindowEvent.Kind.ValueType  # 3
    KIND_RESIZED: RailWindowEvent.Kind.ValueType  # 4
    KIND_MINIMIZED: RailWindowEvent.Kind.ValueType  # 5
    KIND_MAXIMIZED: RailWindowEvent.Kind.ValueType  # 6
    KIND_RESTORED: RailWindowEvent.Kind.ValueType  # 7
    KIND_FOCUS_GAINED: RailWindowEvent.Kind.ValueType  # 8
    KIND_FOCUS_LOST: RailWindowEvent.Kind.ValueType  # 9
    KIND_TITLE_CHANGED: RailWindowEvent.Kind.ValueType  # 10
    KIND_ICON_CHANGED: RailWindowEvent.Kind.ValueType  # 11

    WINDOW_ID_FIELD_NUMBER: _builtins.int
    PROCESS_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    GEOMETRY_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    ICON_PNG_FIELD_NUMBER: _builtins.int
    window_id: _builtins.int
    """HWND"""
    process_id: _builtins.int
    kind: Global___RailWindowEvent.Kind.ValueType
    title: _builtins.str
    icon_png: _builtins.bytes
    """wypełniane tylko dla CREATED / ICON_CHANGED"""
    @_builtins.property
    def geometry(self) -> Global___Rect:
        """Geometria znacząca tylko dla CREATED / MOVED / RESIZED."""

    def __init__(
        self,
        *,
        window_id: _builtins.int = ...,
        process_id: _builtins.int = ...,
        kind: Global___RailWindowEvent.Kind.ValueType = ...,
        geometry: Global___Rect | None = ...,
        title: _builtins.str = ...,
        icon_png: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["geometry", b"geometry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["geometry", b"geometry", "icon_png", b"icon_png", "kind", b"kind", "process_id", b"process_id", "title", b"title", "window_id", b"window_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RailWindowEvent: _TypeAlias = RailWindowEvent  # noqa: Y015

@_typing.final
class Rect(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    x: _builtins.int
    y: _builtins.int
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        x: _builtins.int = ...,
        y: _builtins.int = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "width", b"width", "x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Rect: _TypeAlias = Rect  # noqa: Y015

@_typing.final
class SessionClosed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REASON_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    reason: Global___SessionTerminate.Reason.ValueType
    detail: _builtins.str
    def __init__(
        self,
        *,
        reason: Global___SessionTerminate.Reason.ValueType = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionClosed: _TypeAlias = SessionClosed  # noqa: Y015

@_typing.final
class VerifyCredentialsRequest(_message.Message):
    """-----------------------------------------------------------------------------
    Auth health-check (DEC-0001 Windows password lifecycle).
    Host inicjuje request przed każdym RAIL launch; Guest woła LogonUserW
    (LOGON32_LOGON_NETWORK — najtańsze, nie tworzy desktopu) i odpowiada.
    Plaintext password w ramce jest akceptowalne, bo: (a) mTLS na kanale,
    (b) per-frame AuthContext (fingerprint+nonce+seq), (c) AF_VSOCK nie
    wychodzi poza host. request_id koreluje request z odpowiedzią; gdyby
    kiedyś było wiele in-flight verifies, host musi je rozróżnić.
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    """UUID; koreluje z VerifyCredentialsResult"""
    username: _builtins.str
    """np. "crossdesk" — z ~/.config/crossdesk/vm.toml"""
    password: _builtins.str
    """plaintext na czas RPC"""
    domain: _builtins.str
    """optional; "" lub "." = local account"""
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        username: _builtins.str = ...,
        password: _builtins.str = ...,
        domain: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["domain", b"domain", "password", b"password", "request_id", b"request_id", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VerifyCredentialsRequest: _TypeAlias = VerifyCredentialsRequest  # noqa: Y015

@_typing.final
class VerifyCredentialsResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[VerifyCredentialsResult._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_UNSPECIFIED: VerifyCredentialsResult._Status.ValueType  # 0
        STATUS_OK: VerifyCredentialsResult._Status.ValueType  # 1
        STATUS_FAIL_BAD_CREDENTIALS: VerifyCredentialsResult._Status.ValueType  # 2
        """ERROR_LOGON_FAILURE"""
        STATUS_FAIL_ACCOUNT_LOCKED: VerifyCredentialsResult._Status.ValueType  # 3
        """ERROR_ACCOUNT_LOCKED_OUT"""
        STATUS_FAIL_PASSWORD_EXPIRED: VerifyCredentialsResult._Status.ValueType  # 4
        """ERROR_PASSWORD_EXPIRED / MUST_CHANGE"""
        STATUS_UNAVAILABLE: VerifyCredentialsResult._Status.ValueType  # 5
        """guest LSA niedostępne / agent error"""

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_UNSPECIFIED: VerifyCredentialsResult.Status.ValueType  # 0
    STATUS_OK: VerifyCredentialsResult.Status.ValueType  # 1
    STATUS_FAIL_BAD_CREDENTIALS: VerifyCredentialsResult.Status.ValueType  # 2
    """ERROR_LOGON_FAILURE"""
    STATUS_FAIL_ACCOUNT_LOCKED: VerifyCredentialsResult.Status.ValueType  # 3
    """ERROR_ACCOUNT_LOCKED_OUT"""
    STATUS_FAIL_PASSWORD_EXPIRED: VerifyCredentialsResult.Status.ValueType  # 4
    """ERROR_PASSWORD_EXPIRED / MUST_CHANGE"""
    STATUS_UNAVAILABLE: VerifyCredentialsResult.Status.ValueType  # 5
    """guest LSA niedostępne / agent error"""

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    WIN32_ERROR_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    """odbicie z requesta"""
    status: Global___VerifyCredentialsResult.Status.ValueType
    detail: _builtins.str
    """human-readable; bezpieczne do logowania"""
    win32_error: _builtins.int
    """surowy GetLastError dla diagnostyki"""
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        status: Global___VerifyCredentialsResult.Status.ValueType = ...,
        detail: _builtins.str = ...,
        win32_error: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "request_id", b"request_id", "status", b"status", "win32_error", b"win32_error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VerifyCredentialsResult: _TypeAlias = VerifyCredentialsResult  # noqa: Y015
