# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from crossdesk.v1 import control_pb2 as crossdesk_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in crossdesk/v1/control_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ControlServiceStub(object):
    """=============================================================================
    CrossDesk Control Plane — cykl życia sesji + zdarzenia okien RAIL.

    Transport: gRPC over AF_VSOCK z mTLS na warstwie kanału gRPC. Każdy frame
    niezależnie nosi AuthContext (defense-in-depth wobec CID collision i replay
    — patrz common.proto).

    SESSION FSM (driven by ControlService.OpenSession bidi stream):

    ClientHello                ServerAccept
    HANDSHAKE ───────────────▶ AUTHENTICATING ─────────────▶ AUTHENTICATED
    ▲                            │                              │
    │                            │ AuthFailure                  │ Ready
    └────────────────────────────┘                              ▼
    READY ◀────┐
    │      │
    AppLaunchRequest  │      │
    ▼      │
    LAUNCHING_APP  │
    │      │
    AppLaunched  │      │
    ▼      │
    APP_RUNNING ───┘
    │  AppExit
    │
    SessionTerminate  │
    ▼
    DRAINING
    │
    all RAIL windows closed   │
    ▼
    CLOSED (terminal)

    Każdy nieoczekiwany błąd na strumieniu ⇒ CLOSED + tear-down kanału.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.stream_stream(
            "/crossdesk.v1.ControlService/OpenSession",
            request_serializer=crossdesk_dot_v1_dot_control__pb2.ClientFrame.SerializeToString,
            response_deserializer=crossdesk_dot_v1_dot_control__pb2.ServerFrame.FromString,
            _registered_method=True,
        )


class ControlServiceServicer(object):
    """=============================================================================
    CrossDesk Control Plane — cykl życia sesji + zdarzenia okien RAIL.

    Transport: gRPC over AF_VSOCK z mTLS na warstwie kanału gRPC. Każdy frame
    niezależnie nosi AuthContext (defense-in-depth wobec CID collision i replay
    — patrz common.proto).

    SESSION FSM (driven by ControlService.OpenSession bidi stream):

    ClientHello                ServerAccept
    HANDSHAKE ───────────────▶ AUTHENTICATING ─────────────▶ AUTHENTICATED
    ▲                            │                              │
    │                            │ AuthFailure                  │ Ready
    └────────────────────────────┘                              ▼
    READY ◀────┐
    │      │
    AppLaunchRequest  │      │
    ▼      │
    LAUNCHING_APP  │
    │      │
    AppLaunched  │      │
    ▼      │
    APP_RUNNING ───┘
    │  AppExit
    │
    SessionTerminate  │
    ▼
    DRAINING
    │
    all RAIL windows closed   │
    ▼
    CLOSED (terminal)

    Każdy nieoczekiwany błąd na strumieniu ⇒ CLOSED + tear-down kanału.
    =============================================================================

    """

    def OpenSession(self, request_iterator, context):
        """Bidirectional. Host inicjuje; Guest multipleksuje RailWindowEvent i
        AppLifecycleEvent z powrotem tym samym strumieniem, żeby zachować
        kolejność względem komend kontrolnych.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "OpenSession": grpc.stream_stream_rpc_method_handler(
            servicer.OpenSession,
            request_deserializer=crossdesk_dot_v1_dot_control__pb2.ClientFrame.FromString,
            response_serializer=crossdesk_dot_v1_dot_control__pb2.ServerFrame.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "crossdesk.v1.ControlService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "crossdesk.v1.ControlService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """=============================================================================
    CrossDesk Control Plane — cykl życia sesji + zdarzenia okien RAIL.

    Transport: gRPC over AF_VSOCK z mTLS na warstwie kanału gRPC. Każdy frame
    niezależnie nosi AuthContext (defense-in-depth wobec CID collision i replay
    — patrz common.proto).

    SESSION FSM (driven by ControlService.OpenSession bidi stream):

    ClientHello                ServerAccept
    HANDSHAKE ───────────────▶ AUTHENTICATING ─────────────▶ AUTHENTICATED
    ▲                            │                              │
    │                            │ AuthFailure                  │ Ready
    └────────────────────────────┘                              ▼
    READY ◀────┐
    │      │
    AppLaunchRequest  │      │
    ▼      │
    LAUNCHING_APP  │
    │      │
    AppLaunched  │      │
    ▼      │
    APP_RUNNING ───┘
    │  AppExit
    │
    SessionTerminate  │
    ▼
    DRAINING
    │
    all RAIL windows closed   │
    ▼
    CLOSED (terminal)

    Każdy nieoczekiwany błąd na strumieniu ⇒ CLOSED + tear-down kanału.
    =============================================================================

    """

    @staticmethod
    def OpenSession(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/crossdesk.v1.ControlService/OpenSession",
            crossdesk_dot_v1_dot_control__pb2.ClientFrame.SerializeToString,
            crossdesk_dot_v1_dot_control__pb2.ServerFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
