"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from crossdesk.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ShareHostFrame(_message.Message):
    """=============================================================================
    Host → Guest
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTH_FIELD_NUMBER: _builtins.int
    SENT_AT_FIELD_NUMBER: _builtins.int
    MOUNT_FIELD_NUMBER: _builtins.int
    DETACH_FIELD_NUMBER: _builtins.int
    LOCK_QUERY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def auth(self) -> _common_pb2.AuthContext: ...
    @_builtins.property
    def sent_at(self) -> _common_pb2.TimingMark: ...
    @_builtins.property
    def mount(self) -> Global___MountRequest: ...
    @_builtins.property
    def detach(self) -> Global___DetachRequest: ...
    @_builtins.property
    def lock_query(self) -> Global___LockQuery: ...
    def __init__(
        self,
        *,
        auth: _common_pb2.AuthContext | None = ...,
        sent_at: _common_pb2.TimingMark | None = ...,
        mount: Global___MountRequest | None = ...,
        detach: Global___DetachRequest | None = ...,
        lock_query: Global___LockQuery | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth", "detach", b"detach", "lock_query", b"lock_query", "mount", b"mount", "payload", b"payload", "sent_at", b"sent_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth", "detach", b"detach", "lock_query", b"lock_query", "mount", b"mount", "payload", b"payload", "sent_at", b"sent_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["mount", "detach", "lock_query"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ShareHostFrame: _TypeAlias = ShareHostFrame  # noqa: Y015

@_typing.final
class MountRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _AccessMode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AccessModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MountRequest._AccessMode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ACCESS_UNSPECIFIED: MountRequest._AccessMode.ValueType  # 0
        ACCESS_READ_ONLY: MountRequest._AccessMode.ValueType  # 1
        ACCESS_READ_WRITE: MountRequest._AccessMode.ValueType  # 2

    class AccessMode(_AccessMode, metaclass=_AccessModeEnumTypeWrapper): ...
    ACCESS_UNSPECIFIED: MountRequest.AccessMode.ValueType  # 0
    ACCESS_READ_ONLY: MountRequest.AccessMode.ValueType  # 1
    ACCESS_READ_WRITE: MountRequest.AccessMode.ValueType  # 2

    SHARE_ID_FIELD_NUMBER: _builtins.int
    GUEST_DRIVE_LETTER_FIELD_NUMBER: _builtins.int
    ACCESS_MODE_FIELD_NUMBER: _builtins.int
    FOCAL_FILENAME_FIELD_NUMBER: _builtins.int
    IDLE_RELEASE_AFTER_FIELD_NUMBER: _builtins.int
    MOUNT_TOKEN_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    """UUID; każdy kolejny frame dotyczący tego share'a echo'uje go."""
    guest_drive_letter: _builtins.str
    """Litera dysku, którą Guest MUSI przypisać (np. "X:"). Host pre-wybiera
    wolną literę, żeby uniknąć race'ów z enumeracją mountów po stronie Guesta.
    """
    access_mode: Global___MountRequest.AccessMode.ValueType
    focal_filename: _builtins.str
    """Dokładna nazwa pliku, który użytkownik kliknął na hoście. Guest POWINIEN
    ujawnić tylko tę pozycję (i jawne dependencies otwierane przez aplikację)
    launchowanemu procesowi, żeby skompromitowana aplikacja nie mogła
    enumerować rodzeństwa w katalogu.
    """
    mount_token: _builtins.bytes
    """Mount token: nieprzezroczysty bearer, który Guest MUSI echo'ować w
    każdym frame'ie dotyczącym tego share'a. Niezależny od mTLS; rotowany
    per-share, żeby skompromitowany handle share'a nie mógł zostać użyty
    ponownie po detach.

    WIRE LIMIT: dokładnie 32 bajty (SHA-256 stream-bound HMAC). Implementacje
    MUSZĄ odrzucić frame'y z `mount_token` o innej długości; bez tego limitu
    złośliwy Guest mógłby wyczerpać pamięć Hosta wysyłając wielomegabajtowy
    token na każdym frame'ie.
    """
    @_builtins.property
    def idle_release_after(self) -> _duration_pb2.Duration:
        """Po tym oknie braku otwartych uchwytów Host wyśle DetachRequest. Guest
        proaktywnie pre-flushuje bufory w miarę zbliżania się do deadline'u.
        """

    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        guest_drive_letter: _builtins.str = ...,
        access_mode: Global___MountRequest.AccessMode.ValueType = ...,
        focal_filename: _builtins.str = ...,
        idle_release_after: _duration_pb2.Duration | None = ...,
        mount_token: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["idle_release_after", b"idle_release_after"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_mode", b"access_mode", "focal_filename", b"focal_filename", "guest_drive_letter", b"guest_drive_letter", "idle_release_after", b"idle_release_after", "mount_token", b"mount_token", "share_id", b"share_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MountRequest: _TypeAlias = MountRequest  # noqa: Y015

@_typing.final
class DetachRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SHARE_ID_FIELD_NUMBER: _builtins.int
    MOUNT_TOKEN_FIELD_NUMBER: _builtins.int
    FORCE_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    mount_token: _builtins.bytes
    force: _builtins.bool
    """Bypass open-handle check. Wyłącznie incident path; Host MUSI zalogować
    powód i wyemitować ShareIncident{KIND_FORCED_DETACH} przed wysłaniem.
    """
    reason: _builtins.str
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        mount_token: _builtins.bytes = ...,
        force: _builtins.bool = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["force", b"force", "mount_token", b"mount_token", "reason", b"reason", "share_id", b"share_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DetachRequest: _TypeAlias = DetachRequest  # noqa: Y015

@_typing.final
class LockQuery(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SHARE_ID_FIELD_NUMBER: _builtins.int
    MOUNT_TOKEN_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    """On-demand audyt: Host prosi Guesta o enumerację aktualnie trzymanych
    uchwytów. Używane przez supervisor przed decyzją o forced detach.
    """
    mount_token: _builtins.bytes
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        mount_token: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mount_token", b"mount_token", "share_id", b"share_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LockQuery: _TypeAlias = LockQuery  # noqa: Y015

@_typing.final
class ShareGuestFrame(_message.Message):
    """=============================================================================
    Guest → Host
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTH_FIELD_NUMBER: _builtins.int
    SENT_AT_FIELD_NUMBER: _builtins.int
    MOUNT_RESULT_FIELD_NUMBER: _builtins.int
    LOCK_REPORT_FIELD_NUMBER: _builtins.int
    RELEASE_ACK_FIELD_NUMBER: _builtins.int
    DETACH_RESULT_FIELD_NUMBER: _builtins.int
    INCIDENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def auth(self) -> _common_pb2.AuthContext: ...
    @_builtins.property
    def sent_at(self) -> _common_pb2.TimingMark: ...
    @_builtins.property
    def mount_result(self) -> Global___MountResult: ...
    @_builtins.property
    def lock_report(self) -> Global___LockReport: ...
    @_builtins.property
    def release_ack(self) -> Global___ReleaseAck: ...
    @_builtins.property
    def detach_result(self) -> Global___DetachResult: ...
    @_builtins.property
    def incident(self) -> Global___ShareIncident: ...
    def __init__(
        self,
        *,
        auth: _common_pb2.AuthContext | None = ...,
        sent_at: _common_pb2.TimingMark | None = ...,
        mount_result: Global___MountResult | None = ...,
        lock_report: Global___LockReport | None = ...,
        release_ack: Global___ReleaseAck | None = ...,
        detach_result: Global___DetachResult | None = ...,
        incident: Global___ShareIncident | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth", "detach_result", b"detach_result", "incident", b"incident", "lock_report", b"lock_report", "mount_result", b"mount_result", "payload", b"payload", "release_ack", b"release_ack", "sent_at", b"sent_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth", "detach_result", b"detach_result", "incident", b"incident", "lock_report", b"lock_report", "mount_result", b"mount_result", "payload", b"payload", "release_ack", b"release_ack", "sent_at", b"sent_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["mount_result", "lock_report", "release_ack", "detach_result", "incident"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ShareGuestFrame: _TypeAlias = ShareGuestFrame  # noqa: Y015

@_typing.final
class MountResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MountResult._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_UNSPECIFIED: MountResult._Status.ValueType  # 0
        STATUS_MOUNTED: MountResult._Status.ValueType  # 1
        STATUS_DEVICE_NOT_PRESENT: MountResult._Status.ValueType  # 2
        """libvirt attach nie zmaterializował się w czasie"""
        STATUS_DRIVE_LETTER_TAKEN: MountResult._Status.ValueType  # 3
        STATUS_PERMISSION_DENIED: MountResult._Status.ValueType  # 4
        STATUS_INTERNAL_ERROR: MountResult._Status.ValueType  # 5

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_UNSPECIFIED: MountResult.Status.ValueType  # 0
    STATUS_MOUNTED: MountResult.Status.ValueType  # 1
    STATUS_DEVICE_NOT_PRESENT: MountResult.Status.ValueType  # 2
    """libvirt attach nie zmaterializował się w czasie"""
    STATUS_DRIVE_LETTER_TAKEN: MountResult.Status.ValueType  # 3
    STATUS_PERMISSION_DENIED: MountResult.Status.ValueType  # 4
    STATUS_INTERNAL_ERROR: MountResult.Status.ValueType  # 5

    SHARE_ID_FIELD_NUMBER: _builtins.int
    MOUNT_TOKEN_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    mount_token: _builtins.bytes
    status: Global___MountResult.Status.ValueType
    detail: _builtins.str
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        mount_token: _builtins.bytes = ...,
        status: Global___MountResult.Status.ValueType = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "mount_token", b"mount_token", "share_id", b"share_id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MountResult: _TypeAlias = MountResult  # noqa: Y015

@_typing.final
class LockReport(_message.Message):
    """Periodyczny + on-change raport stanu uchwytów po stronie Guesta.
    Host traktuje (open_handles == 0 AND pending_writes_bytes == 0) jako
    warunek konieczny wejścia w RELEASE_PENDING.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHARE_ID_FIELD_NUMBER: _builtins.int
    MOUNT_TOKEN_FIELD_NUMBER: _builtins.int
    OPEN_HANDLES_FIELD_NUMBER: _builtins.int
    PENDING_WRITES_BYTES_FIELD_NUMBER: _builtins.int
    HANDLES_FIELD_NUMBER: _builtins.int
    OBSERVED_AT_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    mount_token: _builtins.bytes
    open_handles: _builtins.int
    pending_writes_bytes: _builtins.int
    """bajty czekające na fsync"""
    @_builtins.property
    def handles(self) -> _containers.RepeatedCompositeFieldContainer[Global___FileHandle]: ...
    @_builtins.property
    def observed_at(self) -> _common_pb2.TimingMark: ...
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        mount_token: _builtins.bytes = ...,
        open_handles: _builtins.int = ...,
        pending_writes_bytes: _builtins.int = ...,
        handles: _abc.Iterable[Global___FileHandle] | None = ...,
        observed_at: _common_pb2.TimingMark | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["observed_at", b"observed_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["handles", b"handles", "mount_token", b"mount_token", "observed_at", b"observed_at", "open_handles", b"open_handles", "pending_writes_bytes", b"pending_writes_bytes", "share_id", b"share_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LockReport: _TypeAlias = LockReport  # noqa: Y015

@_typing.final
class FileHandle(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Mode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FileHandle._Mode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        MODE_UNSPECIFIED: FileHandle._Mode.ValueType  # 0
        MODE_READ: FileHandle._Mode.ValueType  # 1
        MODE_WRITE: FileHandle._Mode.ValueType  # 2
        MODE_READ_WRITE: FileHandle._Mode.ValueType  # 3

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper): ...
    MODE_UNSPECIFIED: FileHandle.Mode.ValueType  # 0
    MODE_READ: FileHandle.Mode.ValueType  # 1
    MODE_WRITE: FileHandle.Mode.ValueType  # 2
    MODE_READ_WRITE: FileHandle.Mode.ValueType  # 3

    PATH_ON_SHARE_FIELD_NUMBER: _builtins.int
    PROCESS_ID_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    EXCLUSIVE_LOCK_FIELD_NUMBER: _builtins.int
    path_on_share: _builtins.str
    process_id: _builtins.int
    mode: Global___FileHandle.Mode.ValueType
    exclusive_lock: _builtins.bool
    def __init__(
        self,
        *,
        path_on_share: _builtins.str = ...,
        process_id: _builtins.int = ...,
        mode: Global___FileHandle.Mode.ValueType = ...,
        exclusive_lock: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exclusive_lock", b"exclusive_lock", "mode", b"mode", "path_on_share", b"path_on_share", "process_id", b"process_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileHandle: _TypeAlias = FileHandle  # noqa: Y015

@_typing.final
class ReleaseAck(_message.Message):
    """Wysyłany WYŁĄCZNIE gdy Guest może udowodnić, że:
      (a) wszystkie handle zamknięte,
      (b) wszystkie dirty pages zflushowane przez NtFlushBuffersFile,
      (c) proces, dla którego share został utworzony, zakończył się LUB
          jawnie zwolnił share.
    To jest jedyny sygnał, na podstawie którego Host detachuje urządzenie
    w ścieżce happy-path. Brak ReleaseAck ⇒ share trwa do idle_release_after.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHARE_ID_FIELD_NUMBER: _builtins.int
    MOUNT_TOKEN_FIELD_NUMBER: _builtins.int
    RELEASED_AT_FIELD_NUMBER: _builtins.int
    TOTAL_BYTES_WRITTEN_FIELD_NUMBER: _builtins.int
    FINAL_HANDLE_COUNT_OBSERVED_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    mount_token: _builtins.bytes
    total_bytes_written: _builtins.int
    final_handle_count_observed: _builtins.int
    """oczekiwane 0; logujemy dla forensyki"""
    @_builtins.property
    def released_at(self) -> _common_pb2.TimingMark: ...
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        mount_token: _builtins.bytes = ...,
        released_at: _common_pb2.TimingMark | None = ...,
        total_bytes_written: _builtins.int = ...,
        final_handle_count_observed: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["released_at", b"released_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["final_handle_count_observed", b"final_handle_count_observed", "mount_token", b"mount_token", "released_at", b"released_at", "share_id", b"share_id", "total_bytes_written", b"total_bytes_written"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReleaseAck: _TypeAlias = ReleaseAck  # noqa: Y015

@_typing.final
class DetachResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DetachResult._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_UNSPECIFIED: DetachResult._Status.ValueType  # 0
        STATUS_DETACHED: DetachResult._Status.ValueType  # 1
        STATUS_BUSY: DetachResult._Status.ValueType  # 2
        """otwarte handle pozostały, force=false"""
        STATUS_NOT_FOUND: DetachResult._Status.ValueType  # 3
        STATUS_INTERNAL_ERROR: DetachResult._Status.ValueType  # 4

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_UNSPECIFIED: DetachResult.Status.ValueType  # 0
    STATUS_DETACHED: DetachResult.Status.ValueType  # 1
    STATUS_BUSY: DetachResult.Status.ValueType  # 2
    """otwarte handle pozostały, force=false"""
    STATUS_NOT_FOUND: DetachResult.Status.ValueType  # 3
    STATUS_INTERNAL_ERROR: DetachResult.Status.ValueType  # 4

    SHARE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    status: Global___DetachResult.Status.ValueType
    detail: _builtins.str
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        status: Global___DetachResult.Status.ValueType = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "share_id", b"share_id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DetachResult: _TypeAlias = DetachResult  # noqa: Y015

@_typing.final
class ShareIncident(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ShareIncident._Kind.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        KIND_UNSPECIFIED: ShareIncident._Kind.ValueType  # 0
        KIND_TOKEN_MISMATCH: ShareIncident._Kind.ValueType  # 1
        KIND_PATH_TRAVERSAL_BLOCKED: ShareIncident._Kind.ValueType  # 2
        """próba ucieczki przez symlink etc."""
        KIND_UNEXPECTED_DETACH: ShareIncident._Kind.ValueType  # 3
        """urządzenie zniknęło w trakcie mount"""
        KIND_WRITE_FAILED: ShareIncident._Kind.ValueType  # 4
        KIND_FORCED_DETACH: ShareIncident._Kind.ValueType  # 5
        """Host wymusił detach mimo otwartych uchwytów"""

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: ShareIncident.Kind.ValueType  # 0
    KIND_TOKEN_MISMATCH: ShareIncident.Kind.ValueType  # 1
    KIND_PATH_TRAVERSAL_BLOCKED: ShareIncident.Kind.ValueType  # 2
    """próba ucieczki przez symlink etc."""
    KIND_UNEXPECTED_DETACH: ShareIncident.Kind.ValueType  # 3
    """urządzenie zniknęło w trakcie mount"""
    KIND_WRITE_FAILED: ShareIncident.Kind.ValueType  # 4
    KIND_FORCED_DETACH: ShareIncident.Kind.ValueType  # 5
    """Host wymusił detach mimo otwartych uchwytów"""

    SHARE_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    OBSERVED_AT_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    kind: Global___ShareIncident.Kind.ValueType
    detail: _builtins.str
    @_builtins.property
    def observed_at(self) -> _common_pb2.TimingMark: ...
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        kind: Global___ShareIncident.Kind.ValueType = ...,
        detail: _builtins.str = ...,
        observed_at: _common_pb2.TimingMark | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["observed_at", b"observed_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "kind", b"kind", "observed_at", b"observed_at", "share_id", b"share_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ShareIncident: _TypeAlias = ShareIncident  # noqa: Y015
