"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from crossdesk.v1 import filesystem_pb2 as _filesystem_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(
    _abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta
): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class FilesystemServiceStub:
    """=============================================================================
    CrossDesk Filesystem Plane — cykl życia JIT VirtioFS share'a.

    MODEL BEZPIECZEŃSTWA (po Red Team)
    ----------------------------------
    Host NIGDY nie mapuje $HOME na stałe. Gdy user dwuklika plik:
      1. Host wylicza MINIMALNY katalog zawierający plik (per-app sandbox po
         stronie host/virtiofs/, NIE naiwny os.path.dirname).
      2. Host hot-pluguje urządzenie VirtioFS w trybie wyznaczonym polityką.
      3. Host CZEKA na ReleaseAck POCHODZĄCY Z GUESTA przed odpięciem.
         Host NIE może zgadnąć, kiedy proces zamknął uchwyty — tylko Guest
         potrafi udowodnić, że wszystkie handle są zamknięte i bufory zflushowane.

    SHARE FSM (perspektywa hosta; mirror po stronie Guesta):

      REQUESTED ──policy ok──▶ ATTACHING ──libvirt attach──▶ ATTACHED
           │                                                      │
           │ policy reject                          Guest mounts  │
           ▼                                                      ▼
         DENIED                                                MOUNTED
                                                                   │
                                                     first open()  │
                                                                   ▼
                                                                IN_USE
                                                                   │
                ┌──────────────────────────────────────────────────┤
                │ open_handles == 0 AND pending_writes_bytes == 0  │
                ▼                                                  │
         RELEASE_PENDING                                           │
                │ ReleaseAck                                       │
                ▼                                                  │
           DETACHING ◀────────────────────────────── (idle TTL elapsed)
                │ libvirt detach-device
                ▼
           DETACHED (terminal)

    Forced path: jeśli supervisor zdecyduje (np. crash agenta, security
    incident), Host wysyła DetachRequest{force=true} i emituje ShareIncident
    z rodzajem KIND_FORCED_DETACH. Guest powinien wówczas wymusić zamknięcie
    uchwytów po swojej stronie i zalogować incident dla forensyki.
    =============================================================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> FilesystemServiceAsyncStub: ...
    ShareChannel: _grpc.StreamStreamMultiCallable[
        _filesystem_pb2.ShareGuestFrame, _filesystem_pb2.ShareHostFrame
    ]
    """Bidirectional. Host pushuje komendy share'a; Guest pushuje raporty stanu
    (mount results, lock reports, release acks, incydenty).
    """

@_typing.type_check_only
class FilesystemServiceAsyncStub(FilesystemServiceStub):
    """=============================================================================
    CrossDesk Filesystem Plane — cykl życia JIT VirtioFS share'a.

    MODEL BEZPIECZEŃSTWA (po Red Team)
    ----------------------------------
    Host NIGDY nie mapuje $HOME na stałe. Gdy user dwuklika plik:
      1. Host wylicza MINIMALNY katalog zawierający plik (per-app sandbox po
         stronie host/virtiofs/, NIE naiwny os.path.dirname).
      2. Host hot-pluguje urządzenie VirtioFS w trybie wyznaczonym polityką.
      3. Host CZEKA na ReleaseAck POCHODZĄCY Z GUESTA przed odpięciem.
         Host NIE może zgadnąć, kiedy proces zamknął uchwyty — tylko Guest
         potrafi udowodnić, że wszystkie handle są zamknięte i bufory zflushowane.

    SHARE FSM (perspektywa hosta; mirror po stronie Guesta):

      REQUESTED ──policy ok──▶ ATTACHING ──libvirt attach──▶ ATTACHED
           │                                                      │
           │ policy reject                          Guest mounts  │
           ▼                                                      ▼
         DENIED                                                MOUNTED
                                                                   │
                                                     first open()  │
                                                                   ▼
                                                                IN_USE
                                                                   │
                ┌──────────────────────────────────────────────────┤
                │ open_handles == 0 AND pending_writes_bytes == 0  │
                ▼                                                  │
         RELEASE_PENDING                                           │
                │ ReleaseAck                                       │
                ▼                                                  │
           DETACHING ◀────────────────────────────── (idle TTL elapsed)
                │ libvirt detach-device
                ▼
           DETACHED (terminal)

    Forced path: jeśli supervisor zdecyduje (np. crash agenta, security
    incident), Host wysyła DetachRequest{force=true} i emituje ShareIncident
    z rodzajem KIND_FORCED_DETACH. Guest powinien wówczas wymusić zamknięcie
    uchwytów po swojej stronie i zalogować incident dla forensyki.
    =============================================================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ShareChannel: _aio.StreamStreamMultiCallable[_filesystem_pb2.ShareGuestFrame, _filesystem_pb2.ShareHostFrame]  # type: ignore[assignment]
    """Bidirectional. Host pushuje komendy share'a; Guest pushuje raporty stanu
    (mount results, lock reports, release acks, incydenty).
    """

class FilesystemServiceServicer(metaclass=_abc_1.ABCMeta):
    """=============================================================================
    CrossDesk Filesystem Plane — cykl życia JIT VirtioFS share'a.

    MODEL BEZPIECZEŃSTWA (po Red Team)
    ----------------------------------
    Host NIGDY nie mapuje $HOME na stałe. Gdy user dwuklika plik:
      1. Host wylicza MINIMALNY katalog zawierający plik (per-app sandbox po
         stronie host/virtiofs/, NIE naiwny os.path.dirname).
      2. Host hot-pluguje urządzenie VirtioFS w trybie wyznaczonym polityką.
      3. Host CZEKA na ReleaseAck POCHODZĄCY Z GUESTA przed odpięciem.
         Host NIE może zgadnąć, kiedy proces zamknął uchwyty — tylko Guest
         potrafi udowodnić, że wszystkie handle są zamknięte i bufory zflushowane.

    SHARE FSM (perspektywa hosta; mirror po stronie Guesta):

      REQUESTED ──policy ok──▶ ATTACHING ──libvirt attach──▶ ATTACHED
           │                                                      │
           │ policy reject                          Guest mounts  │
           ▼                                                      ▼
         DENIED                                                MOUNTED
                                                                   │
                                                     first open()  │
                                                                   ▼
                                                                IN_USE
                                                                   │
                ┌──────────────────────────────────────────────────┤
                │ open_handles == 0 AND pending_writes_bytes == 0  │
                ▼                                                  │
         RELEASE_PENDING                                           │
                │ ReleaseAck                                       │
                ▼                                                  │
           DETACHING ◀────────────────────────────── (idle TTL elapsed)
                │ libvirt detach-device
                ▼
           DETACHED (terminal)

    Forced path: jeśli supervisor zdecyduje (np. crash agenta, security
    incident), Host wysyła DetachRequest{force=true} i emituje ShareIncident
    z rodzajem KIND_FORCED_DETACH. Guest powinien wówczas wymusić zamknięcie
    uchwytów po swojej stronie i zalogować incident dla forensyki.
    =============================================================================
    """

    @_abc_1.abstractmethod
    def ShareChannel(
        self,
        request_iterator: _MaybeAsyncIterator[_filesystem_pb2.ShareGuestFrame],
        context: _ServicerContext,
    ) -> _typing.Union[
        _abc.Iterator[_filesystem_pb2.ShareHostFrame],
        _abc.AsyncIterator[_filesystem_pb2.ShareHostFrame],
    ]:
        """Bidirectional. Host pushuje komendy share'a; Guest pushuje raporty stanu
        (mount results, lock reports, release acks, incydenty).
        """

def add_FilesystemServiceServicer_to_server(
    servicer: FilesystemServiceServicer,
    server: _typing.Union[_grpc.Server, _aio.Server],
) -> None: ...
