# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crossdesk.v1 import filesystem_pb2 as crossdesk_dot_v1_dot_filesystem__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crossdesk/v1/filesystem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilesystemServiceStub(object):
    """=============================================================================
    CrossDesk Filesystem Plane — cykl życia JIT VirtioFS share'a.

    MODEL BEZPIECZEŃSTWA (po Red Team)
    ----------------------------------
    Host NIGDY nie mapuje $HOME na stałe. Gdy user dwuklika plik:
    1. Host wylicza MINIMALNY katalog zawierający plik (per-app sandbox po
    stronie host/virtiofs/, NIE naiwny os.path.dirname).
    2. Host hot-pluguje urządzenie VirtioFS w trybie wyznaczonym polityką.
    3. Host CZEKA na ReleaseAck POCHODZĄCY Z GUESTA przed odpięciem.
    Host NIE może zgadnąć, kiedy proces zamknął uchwyty — tylko Guest
    potrafi udowodnić, że wszystkie handle są zamknięte i bufory zflushowane.

    SHARE FSM (perspektywa hosta; mirror po stronie Guesta):

    REQUESTED ──policy ok──▶ ATTACHING ──libvirt attach──▶ ATTACHED
    │                                                      │
    │ policy reject                          Guest mounts  │
    ▼                                                      ▼
    DENIED                                                MOUNTED
    │
    first open()  │
    ▼
    IN_USE
    │
    ┌──────────────────────────────────────────────────┤
    │ open_handles == 0 AND pending_writes_bytes == 0  │
    ▼                                                  │
    RELEASE_PENDING                                           │
    │ ReleaseAck                                       │
    ▼                                                  │
    DETACHING ◀────────────────────────────── (idle TTL elapsed)
    │ libvirt detach-device
    ▼
    DETACHED (terminal)

    Forced path: jeśli supervisor zdecyduje (np. crash agenta, security
    incident), Host wysyła DetachRequest{force=true} i emituje ShareIncident
    z rodzajem KIND_FORCED_DETACH. Guest powinien wówczas wymusić zamknięcie
    uchwytów po swojej stronie i zalogować incident dla forensyki.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareChannel = channel.stream_stream(
                '/crossdesk.v1.FilesystemService/ShareChannel',
                request_serializer=crossdesk_dot_v1_dot_filesystem__pb2.ShareClientFrame.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_filesystem__pb2.ShareServerFrame.FromString,
                _registered_method=True)


class FilesystemServiceServicer(object):
    """=============================================================================
    CrossDesk Filesystem Plane — cykl życia JIT VirtioFS share'a.

    MODEL BEZPIECZEŃSTWA (po Red Team)
    ----------------------------------
    Host NIGDY nie mapuje $HOME na stałe. Gdy user dwuklika plik:
    1. Host wylicza MINIMALNY katalog zawierający plik (per-app sandbox po
    stronie host/virtiofs/, NIE naiwny os.path.dirname).
    2. Host hot-pluguje urządzenie VirtioFS w trybie wyznaczonym polityką.
    3. Host CZEKA na ReleaseAck POCHODZĄCY Z GUESTA przed odpięciem.
    Host NIE może zgadnąć, kiedy proces zamknął uchwyty — tylko Guest
    potrafi udowodnić, że wszystkie handle są zamknięte i bufory zflushowane.

    SHARE FSM (perspektywa hosta; mirror po stronie Guesta):

    REQUESTED ──policy ok──▶ ATTACHING ──libvirt attach──▶ ATTACHED
    │                                                      │
    │ policy reject                          Guest mounts  │
    ▼                                                      ▼
    DENIED                                                MOUNTED
    │
    first open()  │
    ▼
    IN_USE
    │
    ┌──────────────────────────────────────────────────┤
    │ open_handles == 0 AND pending_writes_bytes == 0  │
    ▼                                                  │
    RELEASE_PENDING                                           │
    │ ReleaseAck                                       │
    ▼                                                  │
    DETACHING ◀────────────────────────────── (idle TTL elapsed)
    │ libvirt detach-device
    ▼
    DETACHED (terminal)

    Forced path: jeśli supervisor zdecyduje (np. crash agenta, security
    incident), Host wysyła DetachRequest{force=true} i emituje ShareIncident
    z rodzajem KIND_FORCED_DETACH. Guest powinien wówczas wymusić zamknięcie
    uchwytów po swojej stronie i zalogować incident dla forensyki.
    =============================================================================

    """

    def ShareChannel(self, request_iterator, context):
        """Bidirectional. Host pushuje komendy share'a; Guest pushuje raporty stanu
        (mount results, lock reports, release acks, incydenty).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareChannel': grpc.stream_stream_rpc_method_handler(
                    servicer.ShareChannel,
                    request_deserializer=crossdesk_dot_v1_dot_filesystem__pb2.ShareClientFrame.FromString,
                    response_serializer=crossdesk_dot_v1_dot_filesystem__pb2.ShareServerFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crossdesk.v1.FilesystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crossdesk.v1.FilesystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilesystemService(object):
    """=============================================================================
    CrossDesk Filesystem Plane — cykl życia JIT VirtioFS share'a.

    MODEL BEZPIECZEŃSTWA (po Red Team)
    ----------------------------------
    Host NIGDY nie mapuje $HOME na stałe. Gdy user dwuklika plik:
    1. Host wylicza MINIMALNY katalog zawierający plik (per-app sandbox po
    stronie host/virtiofs/, NIE naiwny os.path.dirname).
    2. Host hot-pluguje urządzenie VirtioFS w trybie wyznaczonym polityką.
    3. Host CZEKA na ReleaseAck POCHODZĄCY Z GUESTA przed odpięciem.
    Host NIE może zgadnąć, kiedy proces zamknął uchwyty — tylko Guest
    potrafi udowodnić, że wszystkie handle są zamknięte i bufory zflushowane.

    SHARE FSM (perspektywa hosta; mirror po stronie Guesta):

    REQUESTED ──policy ok──▶ ATTACHING ──libvirt attach──▶ ATTACHED
    │                                                      │
    │ policy reject                          Guest mounts  │
    ▼                                                      ▼
    DENIED                                                MOUNTED
    │
    first open()  │
    ▼
    IN_USE
    │
    ┌──────────────────────────────────────────────────┤
    │ open_handles == 0 AND pending_writes_bytes == 0  │
    ▼                                                  │
    RELEASE_PENDING                                           │
    │ ReleaseAck                                       │
    ▼                                                  │
    DETACHING ◀────────────────────────────── (idle TTL elapsed)
    │ libvirt detach-device
    ▼
    DETACHED (terminal)

    Forced path: jeśli supervisor zdecyduje (np. crash agenta, security
    incident), Host wysyła DetachRequest{force=true} i emituje ShareIncident
    z rodzajem KIND_FORCED_DETACH. Guest powinien wówczas wymusić zamknięcie
    uchwytów po swojej stronie i zalogować incident dla forensyki.
    =============================================================================

    """

    @staticmethod
    def ShareChannel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/crossdesk.v1.FilesystemService/ShareChannel',
            crossdesk_dot_v1_dot_filesystem__pb2.ShareClientFrame.SerializeToString,
            crossdesk_dot_v1_dot_filesystem__pb2.ShareServerFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
