"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from crossdesk.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _GuestState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GuestStateEnumTypeWrapper(
    _enum_type_wrapper._EnumTypeWrapper[_GuestState.ValueType], _builtins.type
):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GUEST_STATE_UNSPECIFIED: _GuestState.ValueType  # 0
    GUEST_STATE_BOOTING: _GuestState.ValueType  # 1
    GUEST_STATE_READY: _GuestState.ValueType  # 2
    GUEST_STATE_RAIL_ACTIVE: _GuestState.ValueType  # 3
    GUEST_STATE_FS_BUSY: _GuestState.ValueType  # 4
    """virtiofs flush w toku; toleruj wyższy RTT"""
    GUEST_STATE_DEGRADED: _GuestState.ValueType  # 5
    GUEST_STATE_SHUTTING_DOWN: _GuestState.ValueType  # 6

class GuestState(_GuestState, metaclass=_GuestStateEnumTypeWrapper): ...

GUEST_STATE_UNSPECIFIED: GuestState.ValueType  # 0
GUEST_STATE_BOOTING: GuestState.ValueType  # 1
GUEST_STATE_READY: GuestState.ValueType  # 2
GUEST_STATE_RAIL_ACTIVE: GuestState.ValueType  # 3
GUEST_STATE_FS_BUSY: GuestState.ValueType  # 4
"""virtiofs flush w toku; toleruj wyższy RTT"""
GUEST_STATE_DEGRADED: GuestState.ValueType  # 5
GUEST_STATE_SHUTTING_DOWN: GuestState.ValueType  # 6
Global___GuestState: _TypeAlias = GuestState  # noqa: Y015

class _RecoveryAction:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RecoveryActionEnumTypeWrapper(
    _enum_type_wrapper._EnumTypeWrapper[_RecoveryAction.ValueType], _builtins.type
):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RECOVERY_ACTION_UNSPECIFIED: _RecoveryAction.ValueType  # 0
    RECOVERY_ACTION_NONE: _RecoveryAction.ValueType  # 1
    RECOVERY_ACTION_OBSERVE: _RecoveryAction.ValueType  # 2
    RECOVERY_ACTION_REQUEST_DIAG: _RecoveryAction.ValueType  # 3
    RECOVERY_ACTION_GRACEFUL_SHUTDOWN: _RecoveryAction.ValueType  # 4
    RECOVERY_ACTION_HARD_DESTROY: _RecoveryAction.ValueType  # 5

class RecoveryAction(_RecoveryAction, metaclass=_RecoveryActionEnumTypeWrapper): ...

RECOVERY_ACTION_UNSPECIFIED: RecoveryAction.ValueType  # 0
RECOVERY_ACTION_NONE: RecoveryAction.ValueType  # 1
RECOVERY_ACTION_OBSERVE: RecoveryAction.ValueType  # 2
RECOVERY_ACTION_REQUEST_DIAG: RecoveryAction.ValueType  # 3
RECOVERY_ACTION_GRACEFUL_SHUTDOWN: RecoveryAction.ValueType  # 4
RECOVERY_ACTION_HARD_DESTROY: RecoveryAction.ValueType  # 5
Global___RecoveryAction: _TypeAlias = RecoveryAction  # noqa: Y015

@_typing.final
class HostFrame(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUTH_FIELD_NUMBER: _builtins.int
    PING_FIELD_NUMBER: _builtins.int
    DIRECTIVE_FIELD_NUMBER: _builtins.int
    PROFILE_UPDATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def auth(self) -> _common_pb2.AuthContext: ...
    @_builtins.property
    def ping(self) -> Global___Ping: ...
    @_builtins.property
    def directive(self) -> Global___HostDirective: ...
    @_builtins.property
    def profile_update(self) -> Global___AdaptiveProfile: ...
    def __init__(
        self,
        *,
        auth: _common_pb2.AuthContext | None = ...,
        ping: Global___Ping | None = ...,
        directive: Global___HostDirective | None = ...,
        profile_update: Global___AdaptiveProfile | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "auth",
        b"auth",
        "directive",
        b"directive",
        "payload",
        b"payload",
        "ping",
        b"ping",
        "profile_update",
        b"profile_update",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "auth",
        b"auth",
        "directive",
        b"directive",
        "payload",
        b"payload",
        "ping",
        b"ping",
        "profile_update",
        b"profile_update",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal[
        "ping", "directive", "profile_update"
    ]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal[
        "payload", b"payload"
    ]  # noqa: Y015
    def WhichOneof(
        self, oneof_group: _WhichOneofArgType_payload
    ) -> _WhichOneofReturnType_payload | None: ...

Global___HostFrame: _TypeAlias = HostFrame  # noqa: Y015

@_typing.final
class GuestFrame(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUTH_FIELD_NUMBER: _builtins.int
    PONG_FIELD_NUMBER: _builtins.int
    SIGNAL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def auth(self) -> _common_pb2.AuthContext: ...
    @_builtins.property
    def pong(self) -> Global___Pong: ...
    @_builtins.property
    def signal(self) -> Global___GuestSignal: ...
    def __init__(
        self,
        *,
        auth: _common_pb2.AuthContext | None = ...,
        pong: Global___Pong | None = ...,
        signal: Global___GuestSignal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "auth", b"auth", "payload", b"payload", "pong", b"pong", "signal", b"signal"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "auth", b"auth", "payload", b"payload", "pong", b"pong", "signal", b"signal"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal[
        "pong", "signal"
    ]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal[
        "payload", b"payload"
    ]  # noqa: Y015
    def WhichOneof(
        self, oneof_group: _WhichOneofArgType_payload
    ) -> _WhichOneofReturnType_payload | None: ...

Global___GuestFrame: _TypeAlias = GuestFrame  # noqa: Y015

@_typing.final
class Ping(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: _builtins.int
    HOST_SEND_MONOTONIC_NS_FIELD_NUMBER: _builtins.int
    LAST_OBSERVED_RTT_FIELD_NUMBER: _builtins.int
    sequence: _builtins.int
    host_send_monotonic_ns: _builtins.int
    @_builtins.property
    def last_observed_rtt(self) -> _duration_pb2.Duration:
        """Host echo'uje ostatnio zaobserwowany RTT, żeby Guest mógł adaptować
        własny scheduling (np. odraczać niekrytyczne zadania).
        """

    def __init__(
        self,
        *,
        sequence: _builtins.int = ...,
        host_send_monotonic_ns: _builtins.int = ...,
        last_observed_rtt: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "last_observed_rtt", b"last_observed_rtt"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "host_send_monotonic_ns",
        b"host_send_monotonic_ns",
        "last_observed_rtt",
        b"last_observed_rtt",
        "sequence",
        b"sequence",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Ping: _TypeAlias = Ping  # noqa: Y015

@_typing.final
class Pong(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: _builtins.int
    HOST_SEND_MONOTONIC_NS_FIELD_NUMBER: _builtins.int
    GUEST_RECV_MONOTONIC_NS_FIELD_NUMBER: _builtins.int
    GUEST_SEND_MONOTONIC_NS_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    PRESSURE_FIELD_NUMBER: _builtins.int
    sequence: _builtins.int
    """mirror Ping.sequence"""
    host_send_monotonic_ns: _builtins.int
    """echo verbatim"""
    guest_recv_monotonic_ns: _builtins.int
    """znacznik recv po stronie Guesta"""
    guest_send_monotonic_ns: _builtins.int
    """znacznik send po stronie Guesta"""
    state: Global___GuestState.ValueType
    @_builtins.property
    def pressure(self) -> Global___ResourcePressure: ...
    def __init__(
        self,
        *,
        sequence: _builtins.int = ...,
        host_send_monotonic_ns: _builtins.int = ...,
        guest_recv_monotonic_ns: _builtins.int = ...,
        guest_send_monotonic_ns: _builtins.int = ...,
        state: Global___GuestState.ValueType = ...,
        pressure: Global___ResourcePressure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "pressure", b"pressure"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "guest_recv_monotonic_ns",
        b"guest_recv_monotonic_ns",
        "guest_send_monotonic_ns",
        b"guest_send_monotonic_ns",
        "host_send_monotonic_ns",
        b"host_send_monotonic_ns",
        "pressure",
        b"pressure",
        "sequence",
        b"sequence",
        "state",
        b"state",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Pong: _TypeAlias = Pong  # noqa: Y015

@_typing.final
class ResourcePressure(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CPU_PERCENT_FIELD_NUMBER: _builtins.int
    MEMORY_PERCENT_FIELD_NUMBER: _builtins.int
    DISK_IO_PRESSURE_FIELD_NUMBER: _builtins.int
    cpu_percent: _builtins.int
    """0–100. Raportowane, żeby kontroler virtio-balloon po stronie hosta
    mógł reagować dynamicznym skalowaniem RAM.
    """
    memory_percent: _builtins.int
    disk_io_pressure: _builtins.int
    def __init__(
        self,
        *,
        cpu_percent: _builtins.int = ...,
        memory_percent: _builtins.int = ...,
        disk_io_pressure: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "cpu_percent",
        b"cpu_percent",
        "disk_io_pressure",
        b"disk_io_pressure",
        "memory_percent",
        b"memory_percent",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResourcePressure: _TypeAlias = ResourcePressure  # noqa: Y015

@_typing.final
class AdaptiveProfile(_message.Message):
    """Host-side adaptive parameters wysyłane, gdy Host przelicza próg.
    Guest używa ich jako advisory hints dla własnego pacingu.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EWMA_RTT_FIELD_NUMBER: _builtins.int
    JITTER_FIELD_NUMBER: _builtins.int
    CURRENT_PING_INTERVAL_FIELD_NUMBER: _builtins.int
    MISS_THRESHOLD_FIELD_NUMBER: _builtins.int
    CONSECUTIVE_MISS_COUNT_FIELD_NUMBER: _builtins.int
    NEXT_ACTION_FIELD_NUMBER: _builtins.int
    NEXT_ACTION_AFTER_FIELD_NUMBER: _builtins.int
    consecutive_miss_count: _builtins.int
    next_action: Global___RecoveryAction.ValueType
    @_builtins.property
    def ewma_rtt(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def jitter(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def current_ping_interval(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def miss_threshold(self) -> _duration_pb2.Duration:
        """adaptive timeout"""

    @_builtins.property
    def next_action_after(self) -> _duration_pb2.Duration:
        """exponential backoff"""

    def __init__(
        self,
        *,
        ewma_rtt: _duration_pb2.Duration | None = ...,
        jitter: _duration_pb2.Duration | None = ...,
        current_ping_interval: _duration_pb2.Duration | None = ...,
        miss_threshold: _duration_pb2.Duration | None = ...,
        consecutive_miss_count: _builtins.int = ...,
        next_action: Global___RecoveryAction.ValueType = ...,
        next_action_after: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "current_ping_interval",
        b"current_ping_interval",
        "ewma_rtt",
        b"ewma_rtt",
        "jitter",
        b"jitter",
        "miss_threshold",
        b"miss_threshold",
        "next_action_after",
        b"next_action_after",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "consecutive_miss_count",
        b"consecutive_miss_count",
        "current_ping_interval",
        b"current_ping_interval",
        "ewma_rtt",
        b"ewma_rtt",
        "jitter",
        b"jitter",
        "miss_threshold",
        b"miss_threshold",
        "next_action",
        b"next_action",
        "next_action_after",
        b"next_action_after",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AdaptiveProfile: _TypeAlias = AdaptiveProfile  # noqa: Y015

@_typing.final
class HostDirective(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(
        _enum_type_wrapper._EnumTypeWrapper[HostDirective._Kind.ValueType],
        _builtins.type,
    ):
        DESCRIPTOR: _descriptor.EnumDescriptor
        KIND_UNSPECIFIED: HostDirective._Kind.ValueType  # 0
        KIND_REQUEST_DIAG_DUMP: HostDirective._Kind.ValueType  # 1
        KIND_REQUEST_GRACEFUL_SHUTDOWN: HostDirective._Kind.ValueType  # 2
        KIND_FREEZE_NEW_WORK: HostDirective._Kind.ValueType  # 3
        KIND_RESUME_NEW_WORK: HostDirective._Kind.ValueType  # 4

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: HostDirective.Kind.ValueType  # 0
    KIND_REQUEST_DIAG_DUMP: HostDirective.Kind.ValueType  # 1
    KIND_REQUEST_GRACEFUL_SHUTDOWN: HostDirective.Kind.ValueType  # 2
    KIND_FREEZE_NEW_WORK: HostDirective.Kind.ValueType  # 3
    KIND_RESUME_NEW_WORK: HostDirective.Kind.ValueType  # 4

    KIND_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    kind: Global___HostDirective.Kind.ValueType
    detail: _builtins.str
    def __init__(
        self,
        *,
        kind: Global___HostDirective.Kind.ValueType = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "detail", b"detail", "kind", b"kind"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HostDirective: _TypeAlias = HostDirective  # noqa: Y015

@_typing.final
class GuestSignal(_message.Message):
    """Asynchroniczny self-report z Guesta (event Windows, o którym Host powinien
    wiedzieć między Pongami).
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(
        _enum_type_wrapper._EnumTypeWrapper[GuestSignal._Kind.ValueType], _builtins.type
    ):
        DESCRIPTOR: _descriptor.EnumDescriptor
        KIND_UNSPECIFIED: GuestSignal._Kind.ValueType  # 0
        KIND_SELF_DETECTED_DEGRADATION: GuestSignal._Kind.ValueType  # 1
        KIND_SHUTDOWN_INITIATED_BY_OS: GuestSignal._Kind.ValueType  # 2
        KIND_DRIVER_FAULT: GuestSignal._Kind.ValueType  # 3
        KIND_DIAG_DUMP_READY: GuestSignal._Kind.ValueType  # 4

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: GuestSignal.Kind.ValueType  # 0
    KIND_SELF_DETECTED_DEGRADATION: GuestSignal.Kind.ValueType  # 1
    KIND_SHUTDOWN_INITIATED_BY_OS: GuestSignal.Kind.ValueType  # 2
    KIND_DRIVER_FAULT: GuestSignal.Kind.ValueType  # 3
    KIND_DIAG_DUMP_READY: GuestSignal.Kind.ValueType  # 4

    KIND_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    OBSERVED_AT_FIELD_NUMBER: _builtins.int
    kind: Global___GuestSignal.Kind.ValueType
    detail: _builtins.str
    @_builtins.property
    def observed_at(self) -> _common_pb2.TimingMark: ...
    def __init__(
        self,
        *,
        kind: Global___GuestSignal.Kind.ValueType = ...,
        detail: _builtins.str = ...,
        observed_at: _common_pb2.TimingMark | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "observed_at", b"observed_at"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "detail", b"detail", "kind", b"kind", "observed_at", b"observed_at"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GuestSignal: _TypeAlias = GuestSignal  # noqa: Y015
