# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crossdesk.v1 import heartbeat_pb2 as crossdesk_dot_v1_dot_heartbeat__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crossdesk/v1/heartbeat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeartbeatServiceStub(object):
    """=============================================================================
    CrossDesk Heartbeat Plane — adaptive RTT-based liveness.

    ZASTĘPUJE oryginalny watchdog 3×500 ms. Host liczy EWMA RTT z tego strumienia
    i dynamicznie wyprowadza próg miss. Guest kooperuje, echo'ując własny zegar
    monotoniczny — pozwala to dekomponować latency na: czas na łączu vs. czas
    w schedulerze Guesta vs. clock skew.

    FAILURE-RESPONSE FSM (perspektywa hosta, per-sesja):

    HEALTHY ──ewma_rtt > k1*baseline──▶ DEGRADED
    ▲                                    │
    │ recovery (3 zdrowe ticki)          │ utrzymane przekroczenie
    │                                    ▼
    └──────────────────────────────── PROBING
    │
    │ Guest niereagujący ≥ adaptive_threshold
    ▼
    SOFT_RECOVERY  (HostDirective.GRACEFUL_SHUTDOWN)
    │
    │ brak ack w oknie backoff
    ▼
    HARD_DESTROY   (libvirt destroy + start)

    Backoff między próbami SOFT_RECOVERY jest exponential-with-jitter; Host MUSI
    wyemitować GuestSignal/AdaptiveProfile z RecoveryAction PRZED akcją, żeby
    supervisor mógł zwetować (np. user actively interacting).
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Channel = channel.stream_stream(
                '/crossdesk.v1.HeartbeatService/Channel',
                request_serializer=crossdesk_dot_v1_dot_heartbeat__pb2.GuestFrame.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_heartbeat__pb2.HostFrame.FromString,
                _registered_method=True)


class HeartbeatServiceServicer(object):
    """=============================================================================
    CrossDesk Heartbeat Plane — adaptive RTT-based liveness.

    ZASTĘPUJE oryginalny watchdog 3×500 ms. Host liczy EWMA RTT z tego strumienia
    i dynamicznie wyprowadza próg miss. Guest kooperuje, echo'ując własny zegar
    monotoniczny — pozwala to dekomponować latency na: czas na łączu vs. czas
    w schedulerze Guesta vs. clock skew.

    FAILURE-RESPONSE FSM (perspektywa hosta, per-sesja):

    HEALTHY ──ewma_rtt > k1*baseline──▶ DEGRADED
    ▲                                    │
    │ recovery (3 zdrowe ticki)          │ utrzymane przekroczenie
    │                                    ▼
    └──────────────────────────────── PROBING
    │
    │ Guest niereagujący ≥ adaptive_threshold
    ▼
    SOFT_RECOVERY  (HostDirective.GRACEFUL_SHUTDOWN)
    │
    │ brak ack w oknie backoff
    ▼
    HARD_DESTROY   (libvirt destroy + start)

    Backoff między próbami SOFT_RECOVERY jest exponential-with-jitter; Host MUSI
    wyemitować GuestSignal/AdaptiveProfile z RecoveryAction PRZED akcją, żeby
    supervisor mógł zwetować (np. user actively interacting).
    =============================================================================

    """

    def Channel(self, request_iterator, context):
        """Bidirectional. HOST jest cadence-setterem; Guest MUSI odpowiadać Pongiem
        na każdy Ping nawet w stanie DEGRADED. Guest może asynchronicznie wpychać
        GuestSignal-e między Pongami, żeby zgłosić self-detected issues.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeartbeatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Channel': grpc.stream_stream_rpc_method_handler(
                    servicer.Channel,
                    request_deserializer=crossdesk_dot_v1_dot_heartbeat__pb2.GuestFrame.FromString,
                    response_serializer=crossdesk_dot_v1_dot_heartbeat__pb2.HostFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crossdesk.v1.HeartbeatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crossdesk.v1.HeartbeatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeartbeatService(object):
    """=============================================================================
    CrossDesk Heartbeat Plane — adaptive RTT-based liveness.

    ZASTĘPUJE oryginalny watchdog 3×500 ms. Host liczy EWMA RTT z tego strumienia
    i dynamicznie wyprowadza próg miss. Guest kooperuje, echo'ując własny zegar
    monotoniczny — pozwala to dekomponować latency na: czas na łączu vs. czas
    w schedulerze Guesta vs. clock skew.

    FAILURE-RESPONSE FSM (perspektywa hosta, per-sesja):

    HEALTHY ──ewma_rtt > k1*baseline──▶ DEGRADED
    ▲                                    │
    │ recovery (3 zdrowe ticki)          │ utrzymane przekroczenie
    │                                    ▼
    └──────────────────────────────── PROBING
    │
    │ Guest niereagujący ≥ adaptive_threshold
    ▼
    SOFT_RECOVERY  (HostDirective.GRACEFUL_SHUTDOWN)
    │
    │ brak ack w oknie backoff
    ▼
    HARD_DESTROY   (libvirt destroy + start)

    Backoff między próbami SOFT_RECOVERY jest exponential-with-jitter; Host MUSI
    wyemitować GuestSignal/AdaptiveProfile z RecoveryAction PRZED akcją, żeby
    supervisor mógł zwetować (np. user actively interacting).
    =============================================================================

    """

    @staticmethod
    def Channel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/crossdesk.v1.HeartbeatService/Channel',
            crossdesk_dot_v1_dot_heartbeat__pb2.GuestFrame.SerializeToString,
            crossdesk_dot_v1_dot_heartbeat__pb2.HostFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
