"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from crossdesk.v1 import heartbeat_pb2 as _heartbeat_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(
    _abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta
): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class HeartbeatServiceStub:
    """=============================================================================
    CrossDesk Heartbeat Plane — adaptive RTT-based liveness.

    ZASTĘPUJE oryginalny watchdog 3×500 ms. Host liczy EWMA RTT z tego strumienia
    i dynamicznie wyprowadza próg miss. Guest kooperuje, echo'ując własny zegar
    monotoniczny — pozwala to dekomponować latency na: czas na łączu vs. czas
    w schedulerze Guesta vs. clock skew.

    FAILURE-RESPONSE FSM (perspektywa hosta, per-sesja):

      HEALTHY ──ewma_rtt > k1*baseline──▶ DEGRADED
         ▲                                    │
         │ recovery (3 zdrowe ticki)          │ utrzymane przekroczenie
         │                                    ▼
         └──────────────────────────────── PROBING
                                               │
                                               │ Guest niereagujący ≥ adaptive_threshold
                                               ▼
                                          SOFT_RECOVERY  (HostDirective.GRACEFUL_SHUTDOWN)
                                               │
                                               │ brak ack w oknie backoff
                                               ▼
                                          HARD_DESTROY   (libvirt destroy + start)

    Backoff między próbami SOFT_RECOVERY jest exponential-with-jitter; Host MUSI
    wyemitować GuestSignal/AdaptiveProfile z RecoveryAction PRZED akcją, żeby
    supervisor mógł zwetować (np. user actively interacting).
    =============================================================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> HeartbeatServiceAsyncStub: ...
    Channel: _grpc.StreamStreamMultiCallable[
        _heartbeat_pb2.GuestFrame, _heartbeat_pb2.HostFrame
    ]
    """Bidirectional. HOST jest cadence-setterem; Guest MUSI odpowiadać Pongiem
    na każdy Ping nawet w stanie DEGRADED. Guest może asynchronicznie wpychać
    GuestSignal-e między Pongami, żeby zgłosić self-detected issues.
    """

@_typing.type_check_only
class HeartbeatServiceAsyncStub(HeartbeatServiceStub):
    """=============================================================================
    CrossDesk Heartbeat Plane — adaptive RTT-based liveness.

    ZASTĘPUJE oryginalny watchdog 3×500 ms. Host liczy EWMA RTT z tego strumienia
    i dynamicznie wyprowadza próg miss. Guest kooperuje, echo'ując własny zegar
    monotoniczny — pozwala to dekomponować latency na: czas na łączu vs. czas
    w schedulerze Guesta vs. clock skew.

    FAILURE-RESPONSE FSM (perspektywa hosta, per-sesja):

      HEALTHY ──ewma_rtt > k1*baseline──▶ DEGRADED
         ▲                                    │
         │ recovery (3 zdrowe ticki)          │ utrzymane przekroczenie
         │                                    ▼
         └──────────────────────────────── PROBING
                                               │
                                               │ Guest niereagujący ≥ adaptive_threshold
                                               ▼
                                          SOFT_RECOVERY  (HostDirective.GRACEFUL_SHUTDOWN)
                                               │
                                               │ brak ack w oknie backoff
                                               ▼
                                          HARD_DESTROY   (libvirt destroy + start)

    Backoff między próbami SOFT_RECOVERY jest exponential-with-jitter; Host MUSI
    wyemitować GuestSignal/AdaptiveProfile z RecoveryAction PRZED akcją, żeby
    supervisor mógł zwetować (np. user actively interacting).
    =============================================================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Channel: _aio.StreamStreamMultiCallable[_heartbeat_pb2.GuestFrame, _heartbeat_pb2.HostFrame]  # type: ignore[assignment]
    """Bidirectional. HOST jest cadence-setterem; Guest MUSI odpowiadać Pongiem
    na każdy Ping nawet w stanie DEGRADED. Guest może asynchronicznie wpychać
    GuestSignal-e między Pongami, żeby zgłosić self-detected issues.
    """

class HeartbeatServiceServicer(metaclass=_abc_1.ABCMeta):
    """=============================================================================
    CrossDesk Heartbeat Plane — adaptive RTT-based liveness.

    ZASTĘPUJE oryginalny watchdog 3×500 ms. Host liczy EWMA RTT z tego strumienia
    i dynamicznie wyprowadza próg miss. Guest kooperuje, echo'ując własny zegar
    monotoniczny — pozwala to dekomponować latency na: czas na łączu vs. czas
    w schedulerze Guesta vs. clock skew.

    FAILURE-RESPONSE FSM (perspektywa hosta, per-sesja):

      HEALTHY ──ewma_rtt > k1*baseline──▶ DEGRADED
         ▲                                    │
         │ recovery (3 zdrowe ticki)          │ utrzymane przekroczenie
         │                                    ▼
         └──────────────────────────────── PROBING
                                               │
                                               │ Guest niereagujący ≥ adaptive_threshold
                                               ▼
                                          SOFT_RECOVERY  (HostDirective.GRACEFUL_SHUTDOWN)
                                               │
                                               │ brak ack w oknie backoff
                                               ▼
                                          HARD_DESTROY   (libvirt destroy + start)

    Backoff między próbami SOFT_RECOVERY jest exponential-with-jitter; Host MUSI
    wyemitować GuestSignal/AdaptiveProfile z RecoveryAction PRZED akcją, żeby
    supervisor mógł zwetować (np. user actively interacting).
    =============================================================================
    """

    @_abc_1.abstractmethod
    def Channel(
        self,
        request_iterator: _MaybeAsyncIterator[_heartbeat_pb2.GuestFrame],
        context: _ServicerContext,
    ) -> _typing.Union[
        _abc.Iterator[_heartbeat_pb2.HostFrame],
        _abc.AsyncIterator[_heartbeat_pb2.HostFrame],
    ]:
        """Bidirectional. HOST jest cadence-setterem; Guest MUSI odpowiadać Pongiem
        na każdy Ping nawet w stanie DEGRADED. Guest może asynchronicznie wpychać
        GuestSignal-e między Pongami, żeby zgłosić self-detected issues.
        """

def add_HeartbeatServiceServicer_to_server(
    servicer: HeartbeatServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]
) -> None: ...
