"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Empty(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Empty: _TypeAlias = Empty  # noqa: Y015

@_typing.final
class StatusFrame(_message.Message):
    """-----------------------------------------------------------------------------
    Status stream
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    VM_FIELD_NUMBER: _builtins.int
    HEARTBEAT_FIELD_NUMBER: _builtins.int
    RESOURCES_FIELD_NUMBER: _builtins.int
    RUNNING_APPS_FIELD_NUMBER: _builtins.int
    RECENT_ACTIVITY_FIELD_NUMBER: _builtins.int
    EMITTED_AT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def vm(self) -> Global___VmStatus:
        """Snapshot at this instant. The daemon emits one whenever any field
        changes; identical consecutive snapshots are deduplicated.
        """

    @_builtins.property
    def heartbeat(self) -> Global___HeartbeatStatus: ...
    @_builtins.property
    def resources(self) -> Global___ResourceUsage: ...
    @_builtins.property
    def running_apps(self) -> _containers.RepeatedCompositeFieldContainer[Global___RailAppRunning]: ...
    @_builtins.property
    def recent_activity(self) -> _containers.RepeatedCompositeFieldContainer[Global___RecentActivity]: ...
    @_builtins.property
    def emitted_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        vm: Global___VmStatus | None = ...,
        heartbeat: Global___HeartbeatStatus | None = ...,
        resources: Global___ResourceUsage | None = ...,
        running_apps: _abc.Iterable[Global___RailAppRunning] | None = ...,
        recent_activity: _abc.Iterable[Global___RecentActivity] | None = ...,
        emitted_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["emitted_at", b"emitted_at", "heartbeat", b"heartbeat", "resources", b"resources", "vm", b"vm"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["emitted_at", b"emitted_at", "heartbeat", b"heartbeat", "recent_activity", b"recent_activity", "resources", b"resources", "running_apps", b"running_apps", "vm", b"vm"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StatusFrame: _TypeAlias = StatusFrame  # noqa: Y015

@_typing.final
class VmStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _State:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[VmStatus._State.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATE_UNSPECIFIED: VmStatus._State.ValueType  # 0
        STATE_OFF: VmStatus._State.ValueType  # 1
        STATE_BOOTING: VmStatus._State.ValueType  # 2
        STATE_RUNNING: VmStatus._State.ValueType  # 3
        STATE_SUSPENDED: VmStatus._State.ValueType  # 4
        STATE_HARD_DESTROYING: VmStatus._State.ValueType  # 5

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    STATE_UNSPECIFIED: VmStatus.State.ValueType  # 0
    STATE_OFF: VmStatus.State.ValueType  # 1
    STATE_BOOTING: VmStatus.State.ValueType  # 2
    STATE_RUNNING: VmStatus.State.ValueType  # 3
    STATE_SUSPENDED: VmStatus.State.ValueType  # 4
    STATE_HARD_DESTROYING: VmStatus.State.ValueType  # 5

    STATE_FIELD_NUMBER: _builtins.int
    UPTIME_FIELD_NUMBER: _builtins.int
    LAST_HARD_DESTROY_FIELD_NUMBER: _builtins.int
    state: Global___VmStatus.State.ValueType
    @_builtins.property
    def uptime(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def last_hard_destroy(self) -> _timestamp_pb2.Timestamp:
        """unset if never"""

    def __init__(
        self,
        *,
        state: Global___VmStatus.State.ValueType = ...,
        uptime: _duration_pb2.Duration | None = ...,
        last_hard_destroy: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["last_hard_destroy", b"last_hard_destroy", "uptime", b"uptime"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["last_hard_destroy", b"last_hard_destroy", "state", b"state", "uptime", b"uptime"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VmStatus: _TypeAlias = VmStatus  # noqa: Y015

@_typing.final
class HeartbeatStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FSM_STATE_FIELD_NUMBER: _builtins.int
    EWMA_RTT_FIELD_NUMBER: _builtins.int
    CONSECUTIVE_MISS_COUNT_FIELD_NUMBER: _builtins.int
    SOFT_ATTEMPTS_FIELD_NUMBER: _builtins.int
    AUTH_CONTEXT_REJECTIONS_FIELD_NUMBER: _builtins.int
    fsm_state: _builtins.str
    """Mirror of crossdesk_host.watchdog.State. String rather than enum
    because the Python side already uses string-valued enums and the
    GUI just renders the label.
    """
    consecutive_miss_count: _builtins.int
    soft_attempts: _builtins.int
    auth_context_rejections: _builtins.int
    @_builtins.property
    def ewma_rtt(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        fsm_state: _builtins.str = ...,
        ewma_rtt: _duration_pb2.Duration | None = ...,
        consecutive_miss_count: _builtins.int = ...,
        soft_attempts: _builtins.int = ...,
        auth_context_rejections: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ewma_rtt", b"ewma_rtt"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_context_rejections", b"auth_context_rejections", "consecutive_miss_count", b"consecutive_miss_count", "ewma_rtt", b"ewma_rtt", "fsm_state", b"fsm_state", "soft_attempts", b"soft_attempts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HeartbeatStatus: _TypeAlias = HeartbeatStatus  # noqa: Y015

@_typing.final
class ResourceUsage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CPU_PERCENT_FIELD_NUMBER: _builtins.int
    RAM_PERCENT_FIELD_NUMBER: _builtins.int
    RAM_USED_BYTES_FIELD_NUMBER: _builtins.int
    RAM_TOTAL_BYTES_FIELD_NUMBER: _builtins.int
    DISK_PERCENT_FIELD_NUMBER: _builtins.int
    cpu_percent: _builtins.int
    """0-100"""
    ram_percent: _builtins.int
    ram_used_bytes: _builtins.int
    ram_total_bytes: _builtins.int
    disk_percent: _builtins.int
    def __init__(
        self,
        *,
        cpu_percent: _builtins.int = ...,
        ram_percent: _builtins.int = ...,
        ram_used_bytes: _builtins.int = ...,
        ram_total_bytes: _builtins.int = ...,
        disk_percent: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cpu_percent", b"cpu_percent", "disk_percent", b"disk_percent", "ram_percent", b"ram_percent", "ram_total_bytes", b"ram_total_bytes", "ram_used_bytes", b"ram_used_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResourceUsage: _TypeAlias = ResourceUsage  # noqa: Y015

@_typing.final
class RailAppRunning(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    APP_ID_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    HWND_FIELD_NUMBER: _builtins.int
    PROCESS_ID_FIELD_NUMBER: _builtins.int
    RAM_BYTES_FIELD_NUMBER: _builtins.int
    LAUNCHED_AT_FIELD_NUMBER: _builtins.int
    app_id: _builtins.str
    display_name: _builtins.str
    hwnd: _builtins.int
    process_id: _builtins.int
    ram_bytes: _builtins.int
    @_builtins.property
    def launched_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        app_id: _builtins.str = ...,
        display_name: _builtins.str = ...,
        hwnd: _builtins.int = ...,
        process_id: _builtins.int = ...,
        ram_bytes: _builtins.int = ...,
        launched_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["launched_at", b"launched_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "display_name", b"display_name", "hwnd", b"hwnd", "launched_at", b"launched_at", "process_id", b"process_id", "ram_bytes", b"ram_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RailAppRunning: _TypeAlias = RailAppRunning  # noqa: Y015

@_typing.final
class RecentActivity(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[RecentActivity._Kind.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        KIND_UNSPECIFIED: RecentActivity._Kind.ValueType  # 0
        KIND_APP_LAUNCHED: RecentActivity._Kind.ValueType  # 1
        KIND_APP_EXITED: RecentActivity._Kind.ValueType  # 2
        KIND_FSM_TRANSITION: RecentActivity._Kind.ValueType  # 3
        KIND_MOUNT_OPENED: RecentActivity._Kind.ValueType  # 4
        KIND_MOUNT_CLOSED: RecentActivity._Kind.ValueType  # 5
        KIND_SUSPEND: RecentActivity._Kind.ValueType  # 6
        KIND_RESUME: RecentActivity._Kind.ValueType  # 7
        KIND_HARD_DESTROY: RecentActivity._Kind.ValueType  # 8
        KIND_AUTH_REJECTION: RecentActivity._Kind.ValueType  # 9

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: RecentActivity.Kind.ValueType  # 0
    KIND_APP_LAUNCHED: RecentActivity.Kind.ValueType  # 1
    KIND_APP_EXITED: RecentActivity.Kind.ValueType  # 2
    KIND_FSM_TRANSITION: RecentActivity.Kind.ValueType  # 3
    KIND_MOUNT_OPENED: RecentActivity.Kind.ValueType  # 4
    KIND_MOUNT_CLOSED: RecentActivity.Kind.ValueType  # 5
    KIND_SUSPEND: RecentActivity.Kind.ValueType  # 6
    KIND_RESUME: RecentActivity.Kind.ValueType  # 7
    KIND_HARD_DESTROY: RecentActivity.Kind.ValueType  # 8
    KIND_AUTH_REJECTION: RecentActivity.Kind.ValueType  # 9

    KIND_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    kind: Global___RecentActivity.Kind.ValueType
    detail: _builtins.str
    """human-readable, already i18n'd by the daemon"""
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        kind: Global___RecentActivity.Kind.ValueType = ...,
        detail: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "kind", b"kind", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RecentActivity: _TypeAlias = RecentActivity  # noqa: Y015

@_typing.final
class AppEntry(_message.Message):
    """-----------------------------------------------------------------------------
    App catalog
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Tier:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TierEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AppEntry._Tier.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TIER_UNSPECIFIED: AppEntry._Tier.ValueType  # 0
        TIER_CURATED: AppEntry._Tier.ValueType  # 1
        TIER_DISCOVERED: AppEntry._Tier.ValueType  # 2
        TIER_USER: AppEntry._Tier.ValueType  # 3

    class Tier(_Tier, metaclass=_TierEnumTypeWrapper): ...
    TIER_UNSPECIFIED: AppEntry.Tier.ValueType  # 0
    TIER_CURATED: AppEntry.Tier.ValueType  # 1
    TIER_DISCOVERED: AppEntry.Tier.ValueType  # 2
    TIER_USER: AppEntry.Tier.ValueType  # 3

    APP_ID_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    EXECUTABLE_GUEST_PATH_FIELD_NUMBER: _builtins.int
    MIME_TYPES_FIELD_NUMBER: _builtins.int
    ICON_DATA_URI_FIELD_NUMBER: _builtins.int
    COMPATIBILITY_STARS_FIELD_NUMBER: _builtins.int
    COMPATIBILITY_NOTES_FIELD_NUMBER: _builtins.int
    CATEGORY_FIELD_NUMBER: _builtins.int
    TIER_FIELD_NUMBER: _builtins.int
    app_id: _builtins.str
    display_name: _builtins.str
    executable_guest_path: _builtins.str
    icon_data_uri: _builtins.str
    """"data:image/png;base64,..." or empty"""
    compatibility_stars: _builtins.int
    """0-5; 0 = no rating"""
    compatibility_notes: _builtins.str
    category: _builtins.str
    """"Office", "Adobe", "Built-in", ..."""
    tier: Global___AppEntry.Tier.ValueType
    @_builtins.property
    def mime_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        app_id: _builtins.str = ...,
        display_name: _builtins.str = ...,
        executable_guest_path: _builtins.str = ...,
        mime_types: _abc.Iterable[_builtins.str] | None = ...,
        icon_data_uri: _builtins.str = ...,
        compatibility_stars: _builtins.int = ...,
        compatibility_notes: _builtins.str = ...,
        category: _builtins.str = ...,
        tier: Global___AppEntry.Tier.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "category", b"category", "compatibility_notes", b"compatibility_notes", "compatibility_stars", b"compatibility_stars", "display_name", b"display_name", "executable_guest_path", b"executable_guest_path", "icon_data_uri", b"icon_data_uri", "mime_types", b"mime_types", "tier", b"tier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AppEntry: _TypeAlias = AppEntry  # noqa: Y015

@_typing.final
class MountEntry(_message.Message):
    """-----------------------------------------------------------------------------
    Mounts (Storage pane)
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHARE_ID_FIELD_NUMBER: _builtins.int
    HOST_PATH_FIELD_NUMBER: _builtins.int
    GUEST_PATH_FIELD_NUMBER: _builtins.int
    APP_ID_FIELD_NUMBER: _builtins.int
    PROCESS_ID_FIELD_NUMBER: _builtins.int
    MOUNTED_AT_FIELD_NUMBER: _builtins.int
    OPEN_HANDLES_FIELD_NUMBER: _builtins.int
    PENDING_WRITES_BYTES_FIELD_NUMBER: _builtins.int
    share_id: _builtins.str
    host_path: _builtins.str
    guest_path: _builtins.str
    app_id: _builtins.str
    """which RAIL app holds it"""
    process_id: _builtins.int
    open_handles: _builtins.int
    pending_writes_bytes: _builtins.int
    @_builtins.property
    def mounted_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        share_id: _builtins.str = ...,
        host_path: _builtins.str = ...,
        guest_path: _builtins.str = ...,
        app_id: _builtins.str = ...,
        process_id: _builtins.int = ...,
        mounted_at: _timestamp_pb2.Timestamp | None = ...,
        open_handles: _builtins.int = ...,
        pending_writes_bytes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["mounted_at", b"mounted_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "guest_path", b"guest_path", "host_path", b"host_path", "mounted_at", b"mounted_at", "open_handles", b"open_handles", "pending_writes_bytes", b"pending_writes_bytes", "process_id", b"process_id", "share_id", b"share_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MountEntry: _TypeAlias = MountEntry  # noqa: Y015

@_typing.final
class LaunchRequest(_message.Message):
    """-----------------------------------------------------------------------------
    Imperative actions
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    APP_ID_FIELD_NUMBER: _builtins.int
    FILE_PATH_FIELD_NUMBER: _builtins.int
    app_id: _builtins.str
    file_path: _builtins.str
    """optional; triggers JIT mount"""
    def __init__(
        self,
        *,
        app_id: _builtins.str = ...,
        file_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "file_path", b"file_path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LaunchRequest: _TypeAlias = LaunchRequest  # noqa: Y015

@_typing.final
class LaunchResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OK_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    ok: _builtins.bool
    error: _builtins.str
    """populated when ok=false"""
    request_id: _builtins.str
    """correlates with AppLaunchRequest on guest plane"""
    def __init__(
        self,
        *,
        ok: _builtins.bool = ...,
        error: _builtins.str = ...,
        request_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "ok", b"ok", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LaunchResponse: _TypeAlias = LaunchResponse  # noqa: Y015

@_typing.final
class ActionAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OK_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    ok: _builtins.bool
    detail: _builtins.str
    def __init__(
        self,
        *,
        ok: _builtins.bool = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "ok", b"ok"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActionAck: _TypeAlias = ActionAck  # noqa: Y015

@_typing.final
class CredentialsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_FIELD_NUMBER: _builtins.int
    KEYRING_KEY_FIELD_NUMBER: _builtins.int
    LAST_ROTATED_FIELD_NUMBER: _builtins.int
    username: _builtins.str
    keyring_key: _builtins.str
    """Password intentionally NOT returned in plain over the wire; the
    GUI uses the keyring abstraction to fetch it directly.
    """
    @_builtins.property
    def last_rotated(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        username: _builtins.str = ...,
        keyring_key: _builtins.str = ...,
        last_rotated: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["last_rotated", b"last_rotated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["keyring_key", b"keyring_key", "last_rotated", b"last_rotated", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CredentialsResponse: _TypeAlias = CredentialsResponse  # noqa: Y015

@_typing.final
class DiagnosticsReport(_message.Message):
    """-----------------------------------------------------------------------------
    Diagnostics
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    CHECKS_FIELD_NUMBER: _builtins.int
    ANY_FAILED_FIELD_NUMBER: _builtins.int
    any_failed: _builtins.bool
    @_builtins.property
    def checks(self) -> _containers.RepeatedCompositeFieldContainer[Global___DiagnosticsCheck]: ...
    def __init__(
        self,
        *,
        checks: _abc.Iterable[Global___DiagnosticsCheck] | None = ...,
        any_failed: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["any_failed", b"any_failed", "checks", b"checks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DiagnosticsReport: _TypeAlias = DiagnosticsReport  # noqa: Y015

@_typing.final
class DiagnosticsCheck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DiagnosticsCheck._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_UNSPECIFIED: DiagnosticsCheck._Status.ValueType  # 0
        STATUS_OK: DiagnosticsCheck._Status.ValueType  # 1
        STATUS_WARN: DiagnosticsCheck._Status.ValueType  # 2
        STATUS_FAIL: DiagnosticsCheck._Status.ValueType  # 3

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_UNSPECIFIED: DiagnosticsCheck.Status.ValueType  # 0
    STATUS_OK: DiagnosticsCheck.Status.ValueType  # 1
    STATUS_WARN: DiagnosticsCheck.Status.ValueType  # 2
    STATUS_FAIL: DiagnosticsCheck.Status.ValueType  # 3

    NAME_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    status: Global___DiagnosticsCheck.Status.ValueType
    message: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        status: Global___DiagnosticsCheck.Status.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "name", b"name", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DiagnosticsCheck: _TypeAlias = DiagnosticsCheck  # noqa: Y015

@_typing.final
class DiagnosticBundle(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ZIP_PAYLOAD_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    GENERATED_AT_FIELD_NUMBER: _builtins.int
    zip_payload: _builtins.bytes
    """capped server-side at 16 MB"""
    filename: _builtins.str
    @_builtins.property
    def generated_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        zip_payload: _builtins.bytes = ...,
        filename: _builtins.str = ...,
        generated_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["generated_at", b"generated_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filename", b"filename", "generated_at", b"generated_at", "zip_payload", b"zip_payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DiagnosticBundle: _TypeAlias = DiagnosticBundle  # noqa: Y015

@_typing.final
class SettingsRequest(_message.Message):
    """-----------------------------------------------------------------------------
    Settings
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    DESIRED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def desired(self) -> Global___Settings: ...
    def __init__(
        self,
        *,
        desired: Global___Settings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["desired", b"desired"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["desired", b"desired"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SettingsRequest: _TypeAlias = SettingsRequest  # noqa: Y015

@_typing.final
class SettingsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def current(self) -> Global___Settings: ...
    def __init__(
        self,
        *,
        current: Global___Settings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["current", b"current"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current", b"current"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SettingsResponse: _TypeAlias = SettingsResponse  # noqa: Y015

@_typing.final
class Settings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LANGUAGE_FIELD_NUMBER: _builtins.int
    THEME_FIELD_NUMBER: _builtins.int
    TELEMETRY_ENABLED_FIELD_NUMBER: _builtins.int
    KEYRING_ENABLED_FIELD_NUMBER: _builtins.int
    LEAN_MODE_FIELD_NUMBER: _builtins.int
    NETWORK_MODE_FIELD_NUMBER: _builtins.int
    HIDPI_SCALE_FIELD_NUMBER: _builtins.int
    MULTI_MONITOR_PLACEMENT_FIELD_NUMBER: _builtins.int
    AUTO_SUSPEND_ON_IDLE_FIELD_NUMBER: _builtins.int
    AUTO_SUSPEND_AFTER_FIELD_NUMBER: _builtins.int
    AUTO_SUSPEND_ON_LID_FIELD_NUMBER: _builtins.int
    AUTO_RESUME_ON_LAUNCH_FIELD_NUMBER: _builtins.int
    MISS_THRESHOLD_FIELD_NUMBER: _builtins.int
    RECOVERY_TICKS_FIELD_NUMBER: _builtins.int
    BACKOFF_INITIAL_FIELD_NUMBER: _builtins.int
    MAX_SOFT_ATTEMPTS_FIELD_NUMBER: _builtins.int
    language: _builtins.str
    """"en", "pl", or "auto" """
    theme: _builtins.str
    """"system", "light", "dark" """
    telemetry_enabled: _builtins.bool
    keyring_enabled: _builtins.bool
    lean_mode: _builtins.bool
    network_mode: _builtins.str
    """"nat", "bridged" """
    hidpi_scale: _builtins.int
    """100/140/180; 0 = auto-detect"""
    multi_monitor_placement: _builtins.bool
    auto_suspend_on_idle: _builtins.bool
    """Auto-suspend"""
    auto_suspend_on_lid: _builtins.bool
    auto_resume_on_launch: _builtins.bool
    miss_threshold: _builtins.int
    """FSM tuning (Advanced)"""
    recovery_ticks: _builtins.int
    max_soft_attempts: _builtins.int
    @_builtins.property
    def auto_suspend_after(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def backoff_initial(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        language: _builtins.str = ...,
        theme: _builtins.str = ...,
        telemetry_enabled: _builtins.bool = ...,
        keyring_enabled: _builtins.bool = ...,
        lean_mode: _builtins.bool = ...,
        network_mode: _builtins.str = ...,
        hidpi_scale: _builtins.int = ...,
        multi_monitor_placement: _builtins.bool = ...,
        auto_suspend_on_idle: _builtins.bool = ...,
        auto_suspend_after: _duration_pb2.Duration | None = ...,
        auto_suspend_on_lid: _builtins.bool = ...,
        auto_resume_on_launch: _builtins.bool = ...,
        miss_threshold: _builtins.int = ...,
        recovery_ticks: _builtins.int = ...,
        backoff_initial: _duration_pb2.Duration | None = ...,
        max_soft_attempts: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["auto_suspend_after", b"auto_suspend_after", "backoff_initial", b"backoff_initial"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auto_resume_on_launch", b"auto_resume_on_launch", "auto_suspend_after", b"auto_suspend_after", "auto_suspend_on_idle", b"auto_suspend_on_idle", "auto_suspend_on_lid", b"auto_suspend_on_lid", "backoff_initial", b"backoff_initial", "hidpi_scale", b"hidpi_scale", "keyring_enabled", b"keyring_enabled", "language", b"language", "lean_mode", b"lean_mode", "max_soft_attempts", b"max_soft_attempts", "miss_threshold", b"miss_threshold", "multi_monitor_placement", b"multi_monitor_placement", "network_mode", b"network_mode", "recovery_ticks", b"recovery_ticks", "telemetry_enabled", b"telemetry_enabled", "theme", b"theme"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Settings: _TypeAlias = Settings  # noqa: Y015

@_typing.final
class GetMetricsRequest(_message.Message):
    """-----------------------------------------------------------------------------
    Metrics snapshot
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_PREFIX_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def name_prefix(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Optional: only metrics whose name starts with one of these
        prefixes are returned. Empty list ⇒ every metric in the
        registry (the default for the CLI).
        """

    def __init__(
        self,
        *,
        name_prefix: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name_prefix", b"name_prefix"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetMetricsRequest: _TypeAlias = GetMetricsRequest  # noqa: Y015

@_typing.final
class Metric(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Metric._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TYPE_UNSPECIFIED: Metric._Type.ValueType  # 0
        COUNTER: Metric._Type.ValueType  # 1
        GAUGE: Metric._Type.ValueType  # 2
        HISTOGRAM: Metric._Type.ValueType  # 3

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    TYPE_UNSPECIFIED: Metric.Type.ValueType  # 0
    COUNTER: Metric.Type.ValueType  # 1
    GAUGE: Metric.Type.ValueType  # 2
    HISTOGRAM: Metric.Type.ValueType  # 3

    @_typing.final
    class LabelsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    LABELS_FIELD_NUMBER: _builtins.int
    SCALAR_FIELD_NUMBER: _builtins.int
    HISTOGRAM_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    type: Global___Metric.Type.ValueType
    scalar: _builtins.float
    """counter (rounded to integer caller-side) or gauge"""
    @_builtins.property
    def labels(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Reserved for label support — Phase 7. The current Registry has
        no per-metric labels, so this field is always empty on the wire
        until labelled metrics land.
        """

    @_builtins.property
    def histogram(self) -> Global___HistogramSnapshot: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        type: Global___Metric.Type.ValueType = ...,
        labels: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        scalar: _builtins.float = ...,
        histogram: Global___HistogramSnapshot | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["histogram", b"histogram", "scalar", b"scalar", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["histogram", b"histogram", "labels", b"labels", "name", b"name", "scalar", b"scalar", "type", b"type", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["scalar", "histogram"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___Metric: _TypeAlias = Metric  # noqa: Y015

@_typing.final
class HistogramSnapshot(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    P50_FIELD_NUMBER: _builtins.int
    P95_FIELD_NUMBER: _builtins.int
    P99_FIELD_NUMBER: _builtins.int
    MIN_FIELD_NUMBER: _builtins.int
    MAX_FIELD_NUMBER: _builtins.int
    COUNT_FIELD_NUMBER: _builtins.int
    p50: _builtins.float
    """Percentiles in seconds (or whatever unit the histogram was fed).
    Mirrors hdrhistogram's get_value_at_percentile, scaled back from
    the µs internal representation; min/max are the actual recorded
    extremes, count is the number of samples.
    """
    p95: _builtins.float
    p99: _builtins.float
    min: _builtins.float
    max: _builtins.float
    count: _builtins.int
    def __init__(
        self,
        *,
        p50: _builtins.float = ...,
        p95: _builtins.float = ...,
        p99: _builtins.float = ...,
        min: _builtins.float = ...,
        max: _builtins.float = ...,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "max", b"max", "min", b"min", "p50", b"p50", "p95", b"p95", "p99", b"p99"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HistogramSnapshot: _TypeAlias = HistogramSnapshot  # noqa: Y015

@_typing.final
class GetMetricsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METRICS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def metrics(self) -> _containers.RepeatedCompositeFieldContainer[Global___Metric]: ...
    def __init__(
        self,
        *,
        metrics: _abc.Iterable[Global___Metric] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metrics", b"metrics"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetMetricsResponse: _TypeAlias = GetMetricsResponse  # noqa: Y015
