# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from crossdesk.v1 import mgmt_pb2 as crossdesk_dot_v1_dot_mgmt__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crossdesk/v1/mgmt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagementServiceStub(object):
    """=============================================================================
    CrossDesk Management Plane — local IPC between the GUI / tray / KCM and the
    crossdesk-host daemon. Bound to ``$XDG_RUNTIME_DIR/crossdesk-host.sock``
    (Unix domain socket) — Unix permissions (0600) ARE the authentication.

    This is intentionally a separate proto from the guest-facing plane
    (control / heartbeat / filesystem) so changes here can't accidentally
    break wire-format compatibility with the guest agent.

    No mTLS, no AuthContext per frame: the socket is owned by the same UID
    as the daemon, and PolicyKit gates privileged actions (HardDestroy,
    SettingsLeanModeChange).
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_stream(
                '/crossdesk.v1.ManagementService/Status',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.StatusFrame.FromString,
                _registered_method=True)
        self.ListApps = channel.unary_stream(
                '/crossdesk.v1.ManagementService/ListApps',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.AppEntry.FromString,
                _registered_method=True)
        self.ListDiscoveredApps = channel.unary_stream(
                '/crossdesk.v1.ManagementService/ListDiscoveredApps',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.AppEntry.FromString,
                _registered_method=True)
        self.ListMounts = channel.unary_stream(
                '/crossdesk.v1.ManagementService/ListMounts',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.MountEntry.FromString,
                _registered_method=True)
        self.Launch = channel.unary_unary(
                '/crossdesk.v1.ManagementService/Launch',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.LaunchRequest.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.LaunchResponse.FromString,
                _registered_method=True)
        self.Suspend = channel.unary_unary(
                '/crossdesk.v1.ManagementService/Suspend',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/crossdesk.v1.ManagementService/Resume',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.FromString,
                _registered_method=True)
        self.HardDestroy = channel.unary_unary(
                '/crossdesk.v1.ManagementService/HardDestroy',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.FromString,
                _registered_method=True)
        self.RotateCredentials = channel.unary_unary(
                '/crossdesk.v1.ManagementService/RotateCredentials',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.CredentialsResponse.FromString,
                _registered_method=True)
        self.RunDiagnostics = channel.unary_unary(
                '/crossdesk.v1.ManagementService/RunDiagnostics',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.DiagnosticsReport.FromString,
                _registered_method=True)
        self.ExportDiagnosticBundle = channel.unary_unary(
                '/crossdesk.v1.ManagementService/ExportDiagnosticBundle',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.DiagnosticBundle.FromString,
                _registered_method=True)
        self.UpdateSettings = channel.unary_unary(
                '/crossdesk.v1.ManagementService/UpdateSettings',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.SettingsRequest.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.SettingsResponse.FromString,
                _registered_method=True)
        self.ReadSettings = channel.unary_unary(
                '/crossdesk.v1.ManagementService/ReadSettings',
                request_serializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
                response_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.SettingsResponse.FromString,
                _registered_method=True)


class ManagementServiceServicer(object):
    """=============================================================================
    CrossDesk Management Plane — local IPC between the GUI / tray / KCM and the
    crossdesk-host daemon. Bound to ``$XDG_RUNTIME_DIR/crossdesk-host.sock``
    (Unix domain socket) — Unix permissions (0600) ARE the authentication.

    This is intentionally a separate proto from the guest-facing plane
    (control / heartbeat / filesystem) so changes here can't accidentally
    break wire-format compatibility with the guest agent.

    No mTLS, no AuthContext per frame: the socket is owned by the same UID
    as the daemon, and PolicyKit gates privileged actions (HardDestroy,
    SettingsLeanModeChange).
    =============================================================================

    """

    def Status(self, request, context):
        """Streaming overview of the host's current state. The GUI subscribes
        once when it opens; the daemon pushes a new frame on every state
        change (FSM transition, mount appearing/disappearing, RAIL window
        event, recovery action). Plain HEALTHY ticks are coalesced to at
        most one push per second to avoid wire churn.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApps(self, request, context):
        """List apps the host is willing to launch. ``ListApps`` returns the
        curated + user-added tiers; ``ListDiscoveredApps`` returns the
        guest-side registry-scan result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDiscoveredApps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMounts(self, request, context):
        """Active JIT VirtioFS shares. Stream so the GUI's Storage pane sees
        mounts appear and disappear in real time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Launch(self, request, context):
        """Imperative actions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Suspend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HardDestroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportDiagnosticBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSettings(self, request, context):
        """Settings round-trip: GUI sends the desired settings, daemon writes
        them to disk, replies with the resulting state (so the GUI can
        see what was clamped/normalised).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_stream_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.StatusFrame.SerializeToString,
            ),
            'ListApps': grpc.unary_stream_rpc_method_handler(
                    servicer.ListApps,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.AppEntry.SerializeToString,
            ),
            'ListDiscoveredApps': grpc.unary_stream_rpc_method_handler(
                    servicer.ListDiscoveredApps,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.AppEntry.SerializeToString,
            ),
            'ListMounts': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMounts,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.MountEntry.SerializeToString,
            ),
            'Launch': grpc.unary_unary_rpc_method_handler(
                    servicer.Launch,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.LaunchRequest.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.LaunchResponse.SerializeToString,
            ),
            'Suspend': grpc.unary_unary_rpc_method_handler(
                    servicer.Suspend,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.SerializeToString,
            ),
            'HardDestroy': grpc.unary_unary_rpc_method_handler(
                    servicer.HardDestroy,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.SerializeToString,
            ),
            'RotateCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateCredentials,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.CredentialsResponse.SerializeToString,
            ),
            'RunDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDiagnostics,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.DiagnosticsReport.SerializeToString,
            ),
            'ExportDiagnosticBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportDiagnosticBundle,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.DiagnosticBundle.SerializeToString,
            ),
            'UpdateSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSettings,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.SettingsRequest.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.SettingsResponse.SerializeToString,
            ),
            'ReadSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSettings,
                    request_deserializer=crossdesk_dot_v1_dot_mgmt__pb2.Empty.FromString,
                    response_serializer=crossdesk_dot_v1_dot_mgmt__pb2.SettingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crossdesk.v1.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crossdesk.v1.ManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """=============================================================================
    CrossDesk Management Plane — local IPC between the GUI / tray / KCM and the
    crossdesk-host daemon. Bound to ``$XDG_RUNTIME_DIR/crossdesk-host.sock``
    (Unix domain socket) — Unix permissions (0600) ARE the authentication.

    This is intentionally a separate proto from the guest-facing plane
    (control / heartbeat / filesystem) so changes here can't accidentally
    break wire-format compatibility with the guest agent.

    No mTLS, no AuthContext per frame: the socket is owned by the same UID
    as the daemon, and PolicyKit gates privileged actions (HardDestroy,
    SettingsLeanModeChange).
    =============================================================================

    """

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/crossdesk.v1.ManagementService/Status',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.StatusFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/crossdesk.v1.ManagementService/ListApps',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.AppEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDiscoveredApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/crossdesk.v1.ManagementService/ListDiscoveredApps',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.AppEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/crossdesk.v1.ManagementService/ListMounts',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.MountEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Launch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/Launch',
            crossdesk_dot_v1_dot_mgmt__pb2.LaunchRequest.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.LaunchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Suspend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/Suspend',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/Resume',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HardDestroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/HardDestroy',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.ActionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/RotateCredentials',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.CredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/RunDiagnostics',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.DiagnosticsReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportDiagnosticBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/ExportDiagnosticBundle',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.DiagnosticBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/UpdateSettings',
            crossdesk_dot_v1_dot_mgmt__pb2.SettingsRequest.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.SettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crossdesk.v1.ManagementService/ReadSettings',
            crossdesk_dot_v1_dot_mgmt__pb2.Empty.SerializeToString,
            crossdesk_dot_v1_dot_mgmt__pb2.SettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
