"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from crossdesk.v1 import mgmt_pb2 as _mgmt_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ManagementServiceStub:
    """=============================================================================
    CrossDesk Management Plane — local IPC between the GUI / tray / KCM and the
    crossdesk-host daemon. Bound to ``$XDG_RUNTIME_DIR/crossdesk-host.sock``
    (Unix domain socket) — Unix permissions (0600) ARE the authentication.

    This is intentionally a separate proto from the guest-facing plane
    (control / heartbeat / filesystem) so changes here can't accidentally
    break wire-format compatibility with the guest agent.

    No mTLS, no AuthContext per frame: the socket is owned by the same UID
    as the daemon, and PolicyKit gates privileged actions (HardDestroy,
    SettingsLeanModeChange).
    =============================================================================
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ManagementServiceAsyncStub: ...
    Status: _grpc.UnaryStreamMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.StatusFrame]
    """Streaming overview of the host's current state. The GUI subscribes
    once when it opens; the daemon pushes a new frame on every state
    change (FSM transition, mount appearing/disappearing, RAIL window
    event, recovery action). Plain HEALTHY ticks are coalesced to at
    most one push per second to avoid wire churn.
    """
    ListApps: _grpc.UnaryStreamMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.AppEntry]
    """List apps the host is willing to launch. ``ListApps`` returns the
    curated + user-added tiers; ``ListDiscoveredApps`` returns the
    guest-side registry-scan result.
    """
    ListDiscoveredApps: _grpc.UnaryStreamMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.AppEntry]
    ListMounts: _grpc.UnaryStreamMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.MountEntry]
    """Active JIT VirtioFS shares. Stream so the GUI's Storage pane sees
    mounts appear and disappear in real time.
    """
    Launch: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.LaunchRequest, _mgmt_pb2.LaunchResponse]
    """Imperative actions."""
    Suspend: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.ActionAck]
    Resume: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.ActionAck]
    HardDestroy: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.ActionAck]
    RotateCredentials: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.CredentialsResponse]
    RunDiagnostics: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.DiagnosticsReport]
    ExportDiagnosticBundle: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.DiagnosticBundle]
    UpdateSettings: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.SettingsRequest, _mgmt_pb2.SettingsResponse]
    """Settings round-trip: GUI sends the desired settings, daemon writes
    them to disk, replies with the resulting state (so the GUI can
    see what was clamped/normalised).
    """
    ReadSettings: _grpc.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.SettingsResponse]

@_typing.type_check_only
class ManagementServiceAsyncStub(ManagementServiceStub):
    """=============================================================================
    CrossDesk Management Plane — local IPC between the GUI / tray / KCM and the
    crossdesk-host daemon. Bound to ``$XDG_RUNTIME_DIR/crossdesk-host.sock``
    (Unix domain socket) — Unix permissions (0600) ARE the authentication.

    This is intentionally a separate proto from the guest-facing plane
    (control / heartbeat / filesystem) so changes here can't accidentally
    break wire-format compatibility with the guest agent.

    No mTLS, no AuthContext per frame: the socket is owned by the same UID
    as the daemon, and PolicyKit gates privileged actions (HardDestroy,
    SettingsLeanModeChange).
    =============================================================================
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Status: _aio.UnaryStreamMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.StatusFrame]  # type: ignore[assignment]
    """Streaming overview of the host's current state. The GUI subscribes
    once when it opens; the daemon pushes a new frame on every state
    change (FSM transition, mount appearing/disappearing, RAIL window
    event, recovery action). Plain HEALTHY ticks are coalesced to at
    most one push per second to avoid wire churn.
    """
    ListApps: _aio.UnaryStreamMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.AppEntry]  # type: ignore[assignment]
    """List apps the host is willing to launch. ``ListApps`` returns the
    curated + user-added tiers; ``ListDiscoveredApps`` returns the
    guest-side registry-scan result.
    """
    ListDiscoveredApps: _aio.UnaryStreamMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.AppEntry]  # type: ignore[assignment]
    ListMounts: _aio.UnaryStreamMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.MountEntry]  # type: ignore[assignment]
    """Active JIT VirtioFS shares. Stream so the GUI's Storage pane sees
    mounts appear and disappear in real time.
    """
    Launch: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.LaunchRequest, _mgmt_pb2.LaunchResponse]  # type: ignore[assignment]
    """Imperative actions."""
    Suspend: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.ActionAck]  # type: ignore[assignment]
    Resume: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.ActionAck]  # type: ignore[assignment]
    HardDestroy: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.ActionAck]  # type: ignore[assignment]
    RotateCredentials: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.CredentialsResponse]  # type: ignore[assignment]
    RunDiagnostics: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.DiagnosticsReport]  # type: ignore[assignment]
    ExportDiagnosticBundle: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.DiagnosticBundle]  # type: ignore[assignment]
    UpdateSettings: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.SettingsRequest, _mgmt_pb2.SettingsResponse]  # type: ignore[assignment]
    """Settings round-trip: GUI sends the desired settings, daemon writes
    them to disk, replies with the resulting state (so the GUI can
    see what was clamped/normalised).
    """
    ReadSettings: _aio.UnaryUnaryMultiCallable[_mgmt_pb2.Empty, _mgmt_pb2.SettingsResponse]  # type: ignore[assignment]

class ManagementServiceServicer(metaclass=_abc_1.ABCMeta):
    """=============================================================================
    CrossDesk Management Plane — local IPC between the GUI / tray / KCM and the
    crossdesk-host daemon. Bound to ``$XDG_RUNTIME_DIR/crossdesk-host.sock``
    (Unix domain socket) — Unix permissions (0600) ARE the authentication.

    This is intentionally a separate proto from the guest-facing plane
    (control / heartbeat / filesystem) so changes here can't accidentally
    break wire-format compatibility with the guest agent.

    No mTLS, no AuthContext per frame: the socket is owned by the same UID
    as the daemon, and PolicyKit gates privileged actions (HardDestroy,
    SettingsLeanModeChange).
    =============================================================================
    """

    @_abc_1.abstractmethod
    def Status(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_mgmt_pb2.StatusFrame], _abc.AsyncIterator[_mgmt_pb2.StatusFrame]]:
        """Streaming overview of the host's current state. The GUI subscribes
        once when it opens; the daemon pushes a new frame on every state
        change (FSM transition, mount appearing/disappearing, RAIL window
        event, recovery action). Plain HEALTHY ticks are coalesced to at
        most one push per second to avoid wire churn.
        """

    @_abc_1.abstractmethod
    def ListApps(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_mgmt_pb2.AppEntry], _abc.AsyncIterator[_mgmt_pb2.AppEntry]]:
        """List apps the host is willing to launch. ``ListApps`` returns the
        curated + user-added tiers; ``ListDiscoveredApps`` returns the
        guest-side registry-scan result.
        """

    @_abc_1.abstractmethod
    def ListDiscoveredApps(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_mgmt_pb2.AppEntry], _abc.AsyncIterator[_mgmt_pb2.AppEntry]]: ...

    @_abc_1.abstractmethod
    def ListMounts(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_mgmt_pb2.MountEntry], _abc.AsyncIterator[_mgmt_pb2.MountEntry]]:
        """Active JIT VirtioFS shares. Stream so the GUI's Storage pane sees
        mounts appear and disappear in real time.
        """

    @_abc_1.abstractmethod
    def Launch(
        self,
        request: _mgmt_pb2.LaunchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.LaunchResponse, _abc.Awaitable[_mgmt_pb2.LaunchResponse]]:
        """Imperative actions."""

    @_abc_1.abstractmethod
    def Suspend(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.ActionAck, _abc.Awaitable[_mgmt_pb2.ActionAck]]: ...

    @_abc_1.abstractmethod
    def Resume(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.ActionAck, _abc.Awaitable[_mgmt_pb2.ActionAck]]: ...

    @_abc_1.abstractmethod
    def HardDestroy(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.ActionAck, _abc.Awaitable[_mgmt_pb2.ActionAck]]: ...

    @_abc_1.abstractmethod
    def RotateCredentials(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.CredentialsResponse, _abc.Awaitable[_mgmt_pb2.CredentialsResponse]]: ...

    @_abc_1.abstractmethod
    def RunDiagnostics(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.DiagnosticsReport, _abc.Awaitable[_mgmt_pb2.DiagnosticsReport]]: ...

    @_abc_1.abstractmethod
    def ExportDiagnosticBundle(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.DiagnosticBundle, _abc.Awaitable[_mgmt_pb2.DiagnosticBundle]]: ...

    @_abc_1.abstractmethod
    def UpdateSettings(
        self,
        request: _mgmt_pb2.SettingsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.SettingsResponse, _abc.Awaitable[_mgmt_pb2.SettingsResponse]]:
        """Settings round-trip: GUI sends the desired settings, daemon writes
        them to disk, replies with the resulting state (so the GUI can
        see what was clamped/normalised).
        """

    @_abc_1.abstractmethod
    def ReadSettings(
        self,
        request: _mgmt_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_mgmt_pb2.SettingsResponse, _abc.Awaitable[_mgmt_pb2.SettingsResponse]]: ...

def add_ManagementServiceServicer_to_server(servicer: ManagementServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
